### ISSUE TITLE
Windows Terminal Freezes on Resize

### ISSUE THREAD

**Issue by functionportal** [microsoft/terminal#11903]
### Windows Terminal version

1.11.2921.0

### Windows build number

10.0.22000

### Steps to reproduce

Open terminal with some Ubuntu WSL2 tabs.
Work for a bit to populate the terminal tab contents.
Resize window or change the screen resolution.

### Expected Behavior

Terminal window continues to function and allow input.

### Actual Behavior

Windows Terminal tabs no longer accept input and hang.

**Comment by zadjii-msft** [comment]
Do you have a consistent set of steps of how you're populating the Terminal that repro's this, or is it just random? When the window is hung like this, is _the tab_ hung, or _the entire window_? Like, can you open new tabs that work fine, it's just the original tab that's hung?

When the Terminal is frozen like this, could you grab a dump with Task Manager and send it to us? 

![image](https://user-images.githubusercontent.com/18356694/135876584-e48514d6-26c0-49da-ae28-b8c5d66dc2a3.png)

Thant might be helpful in trying to figure out what's hung.

**Comment by functionportal** [comment]
@zadjii-msft 
The content is random. All the tabs are frozen, but I can open new tabs in the terminal window and they work fine. Next time this happens (which will be sooner rather than later) I'll create a dump file.

**Comment by functionportal** [comment]
@zadjii-msft 
See attached screenshot and dump file:
![image](https://user-images.githubusercontent.com/5348503/145663275-cefa5361-f0c6-4bd0-90fe-72d8f9385b08.png)

**Comment by functionportal** [comment]
http://functionportal.synology.me:5000/sharing/9WJqxVQ2U

**Comment by 19945600523** [comment]
😀

**Comment by zadjii-msft** [comment]
> It's 5gb uncompressed

wow holy crap. Okay, that's probably infeasible to send over email or the other usual channels. The simplest solution here might be to have you open the dump yourself in [WinDBG](https://www.microsoft.com/en-us/p/windbg-preview/9pgjgd53tn86?activetab=pivot:overviewtab). Give it a while to load the symbols, and then type `~*k` in the Command Window. That'll print a stack trace of all the threads. Paste the output here, it should be immediately obvious where the stack overflow is occurring. (I'm guessing it's a SO with that much RAM usage)

**Comment by functionportal** [comment]
[out.txt](https://github.com/microsoft/terminal/files/7803116/out.txt)

**Comment by Nytelife26** [comment]
I'm currently experiencing the same issue. The WSL instance seems to freeze, but I can open new tabs that work just fine.

Additionally, sometimes with multiple tabs if I use one for so long and then come back to the other, it has also frozen. I suspect something might be halting when not in use that fails to wake back up when required.

**Comment by darkmastermindz** [comment]
> I'm currently experiencing the same issue. The WSL instance seems to freeze, but I can open new tabs that work just fine.
> 
> Additionally, sometimes with multiple tabs if I use one for so long and then come back to the other, it has also frozen. I suspect something might be halting when not in use that fails to wake back up when required.

I'm seeing the same behavior

**Comment by darkmastermindz** [comment]
> > I'm currently experiencing the same issue. The WSL instance seems to freeze, but I can open new tabs that work just fine.
> > Additionally, sometimes with multiple tabs if I use one for so long and then come back to the other, it has also frozen. I suspect something might be halting when not in use that fails to wake back up when required.
> 
> I'm seeing the same behavior

Turns out in my case it was oh-my-zsh was causing the issue. Disabling it in .zshrc resolved this for me.

**Comment by ctsyeh** [comment]
This started to happen to me in the past few months.  Never happened before that.

I primarily work in WSL, and I also noticed that during resize, sometimes the Bash PS1 prompt is not displayed correctly; I only get partial output from the prompt.

Windows Terminal
Version: 1.14.1962.0

**Comment by zadjii-msft** [comment]
Hmm. Just linking some other posts that all come to mind:


* #12607 
* #12176 
* #13386
* #13705

I'm starting to think this whole nexus of issues is related

**Comment by zadjii-msft** [comment]
wait hold the phone
https://github.com/microsoft/terminal/issues/11903#issuecomment-991447692

That's a 5GB windowsterminal.exe? That's WAY bigger than expected. That's a crazy memory leak. Terminal should never be running anywhere close to that. But there's no stack overflow, there's no obvious loop without looking at the real symbols. 


None of the other deadlocks are anything like that kind of a leak. 

Any chance, are you running magnifier, or Narrator, or any other sort of accessibility / UIA tool?

note to self: 1.11 did include the ticket_lock


I think there's a way to upload a .dmp to feedback hub, without making FH try to take the dump itself. If you just drag/drop the dmp to the "Attached" section of FH, it _should_ upload it. 

![image](https://user-images.githubusercontent.com/18356694/185668675-22a98b4f-1ea7-4079-be35-d9597ad77285.png)


Can you try that, and share the link here? Hopefully my debugger can pull the symbols

**Comment by sc-angeluzunov** [comment]
Hi @zadjii-msft 

I've been experiencing a similar behavior since recently, where I would minimize the Windows Terminal window and later when trying to return to it, I would discover it got stuck - cannot be restored and can be only closed. I suspect this might be some Windows Store App idling behavior gone bad.

I can start a new Windows Terminal window, no problem there. It's just the one that was minimized that I cannot recover. In this case, I had a Powershell 7 tab running as the only running tab, and wasn't doing anything fancy there.

I've captured a few shots of the process (via Task Manager and Process Explorer), as well as a dump file. My process doesn't have memory runaway like the OP's, but the mem dump is still big - around 300 MB.

![image](https://user-images.githubusercontent.com/84584498/186453249-2fbc6dc4-3992-4dab-b1ac-b44ba54b4ec3.png)
![image](https://user-images.githubusercontent.com/84584498/186453633-c34c7682-06ee-4590-b002-1905e6e985d5.png)

Windows Terminal version: 1.14.1962.0
Windows OS version: Windows 10 Enterprise, 20H2, OS build 19042.1889

Let me know if I can send a link with the dump file via OneDrive or similar.

Thanks!
Angel

**Comment by zadjii-msft** [comment]
@sc-angeluzunov you're seeing #13589, which already has a fix available.

**Comment by sc-angeluzunov** [comment]
Oops, apologies! So that one goes out with 1.16 - good to know.
@zadjii-msft Thanks for the quick reply!

**Comment by zadjii-msft** [comment]
@sc-angeluzunov it's actually already available for 1.14 in https://github.com/microsoft/terminal/releases/tag/v1.14.2281.0

**Comment by richardroberts** [comment]
I've been having the same freezing issue, it happens most often when changing screen resolution, or connecting via remote desktop.  Here's a dump file: https://1drv.ms/u/s!AhK2CLItkDrhgbhVq3DTXs29a0c3bA?e=tRnWDZ

**Comment by stevenhay** [comment]
Also happening to me, too, when resizing the window the terminal contents no longer updates, however it *is* still processing inputs as I can write my vim buffer and quit before opening a new, working, tab.

**Comment by ElDavoo** [comment]
I'm having a different problem, sometimes the whole window hangs on minimize. when i kill terminal, then, i will have un unresponsive "openconsole.exe" on the top left of the screen that is very small and only has the close button. can't consinstently reproduce, it's random. it's been doing that since the latest update on ms store (which is 1.16.2642.0 i think)

**Comment by ElDavoo** [comment]
![image](https://user-images.githubusercontent.com/7345120/197401190-195c0457-6cd0-47ef-86cd-f6e04d662b05.png)
screen of what appears after i kill terminal

**Comment by FalcoXYZ** [comment]
I've experienced the same issue, terminal hangs after resizing my window. (was running 2 terminal tabs and 1 ubuntu wsl) Not sure when it exactly happened, as I just restarted terminal and it seems to be OK now (resizing is OK) so it seems a bit random.

**Comment by zadjii-msft** [comment]
@ElDavoo FWIW what you're seeing is some vatiation on #13640, which I think is related to #13388. 

<hr>

We've got a running theory that the Atlas Rendering Engine, enabled by default on 1.16 Preview, should resolve this, or at least mitigate it greatly.

**Comment by ElDavoo** [comment]
I'll let you know if I'd happens again

**Comment by Slapbox** [comment]
> it's actually already available for 1.14 in

@zadjii-msft I have 1.15.2875.0 but it still freezes a `zsh` shell terminal :(

**Comment by zadjii-msft** [comment]
@Slapbox The comment you quoted, about 1.14, was for an unrelated bug that got roped into this thread. As I said above, we've got a theory that this is fixed in 1.16 Preview, with the atlas engine, but we can't say for sure without a consistent repro.

**Comment by Slapbox** [comment]
@zadjii-msft sorry I meant to update here - it turned out to be the known issue with Git For Windows.

**Comment by ElDavoo** [comment]
> @Slapbox The comment you quoted, about 1.14, was for an unrelated bug that got roped into this thread. As I said above, we've got a theory that this is fixed in 1.16 Preview, with the atlas engine, but we can't say for sure without a consistent repro.

Still happens :( Can't have consistent steps to reproduce. happens sometimes when minimizing.

**Comment by zadjii-msft** [comment]
Hey there's a pile of threads that are all related, and I think I found someone with a better understanding of DX that can help. For the (many) folks in this thread that can reproduce this on demand: 
When the Terminal is frozen like this, could you grab a dump with Task Manager and send it to us? 

![image](https://user-images.githubusercontent.com/18356694/135876584-e48514d6-26c0-49da-ae28-b8c5d66dc2a3.png)

If you've got a file-sharing mechanism you like, that's probably easiest! Otherwise, you can use Feedback Hub:

<details>
<summary>Feedback Hub Instructions (click me)</summary>

You can upload a `.dmp` to Feedback Hub, without making FH try to take the dump itself. If you just drag/drop the dmp to the "Attached" section of FH, it _should_ upload it. 

![image](https://user-images.githubusercontent.com/18356694/185668675-22a98b4f-1ea7-4079-be35-d9597ad77285.png)

Can you try that, and share the link here? Make sure to share the aka.ms link that Feedback Hub generates with the "Share" button - it's impossible to find without that. 

</details>
 
Hopefully we can get to the bottom of this.

**Comment by ElDavoo** [comment]
[there you go](https://unibari-my.sharepoint.com/:u:/g/personal/d_palma6_studenti_uniba_it/EQE8ZrYbCWdEhpWOI8L2m7MBjuOnjMmAetlcUwm5MvkOOQ?e=fO3tpR)

**Comment by ElDavoo** [comment]
[another one](https://unibari-my.sharepoint.com/:u:/g/personal/d_palma6_studenti_uniba_it/EWTonP0F6dBOmkh57mcbDJABrrtMVJSlw7Fs9bvA_wFl0w?e=AA4S9n)

**Comment by pas-de-2** [comment]
The issue has something to do with how oh-my-zsh generates `git_prompt_info`.

I have noticed that resizing the window spawns 2 additional zsh.exe processes. If you kill the top most process in task manager, the prompt unhangs.

**Comment by lhecker** [comment]
This will most likely be fixed by #14959 because it doesn't call any graphics APIs while the console lock is being held.

**Comment by ElDavoo** [comment]
i don't have the problem anymore

**Comment by zadjii-msft** [comment]
Hey we're pretty sure this was fixed at least by Terminal Preview, v1.18. If anyone's still hitting something like this, we should probably start a new thread at this point, considering how much has been refactored and rewritten at this point.
