### ISSUE TITLE
Update theme based on OS preferred color scheme

### ISSUE THREAD

**Issue by sergiubacioiu** [microsoft/terminal#12682]
### Windows Terminal version

1.13.10395.0

### Windows build number

10.0.19044.0

### Steps to reproduce

Open Terminal -> Settings -> Appearance -> Theme and make sure that "Use Windows theme" is active.

After changing the OS color theme the Terminal interface is not updated only after an app restart.

### Expected Behavior

Update theme based on OS preferred color scheme without restarting the app.

### Actual Behavior

The theme is not updated without a restart.

**Comment by j4james** [comment]
This was previously raised in #1230, but that issue is currently closed as "resolution-external", because the problem is fixed in Windows 11. So for now, the answer is that you'll need Windows 11 if you want this to work correct.

That said, I think it might still be possible to get it working in Windows 10. I had a partial solution a while back that looked promising, but I got sidetracked with other stuff and haven't had a chance to get back to it. If/when I do finish that off, the PR should be tracked in #1230.

**Comment by rashil2000** [comment]
I'm using Windows 11 Build 22572 and still facing this issue.

The titlebar does not fully react to system theme change. The whole window needs to be restarted. Even manually changing the value of `"theme"` does not make it react immediately.

**Comment by zadjii-msft** [comment]
@rashil2000 you might be seeing something like #12356. 

I suppose I'll leave this open to handle the Windows 10 fix for #1230, to make it clearer that #1230 isn't fixed on 10.
