### ISSUE TITLE
Keyboard input does not work on 10.0.22581.0+ / 22H2

### ISSUE THREAD

**Issue by asgeirn** [microsoft/terminal#12746]
### Windows Terminal version

1.12.10393.0

### Windows build number

10.0.22581.0

### Steps to reproduce

1. Upgrade to 22H2 build 22581
2. Install Windows Terminal (any version - tested both regular and preview in Store) and latest from GitHub Releases
3. Try typing in the window.  Sometimes one or two characters appear.
4. Dragging the window is also blocked for some time after typing.

### Expected Behavior

Typing characters in the terminal should behave as intended.

### Actual Behavior

No characters appear, window is frozen (cannot be dragged) for several seconds.

Pasting text works just fine, so command can be entered in Notepad and be pasted to the terminal window.

**Comment by zadjii-msft** [comment]
Sorry to hear about this! We've actually got an internal mail thread discussing something similar right now. Lemme bump that thread and see if I can't get someone on the input team to point you in the direction of some traces to take.

@ebadger here's a external report of that issue we've got the internal thread on.

**Comment by BobbyWibowo** [comment]
Can confirm the same thing happens to me on the same Windows Terminal build and Windows build (received the big update via Windows Update earlier this afternoon).

**Comment by asgeirn** [comment]
Issue seems to have been resolved with release 1.13.10734.0

**Comment by bwets** [comment]
tried installing 1.13.10734.0, issue still here on 22581.100

**Comment by BobbyWibowo** [comment]
The issue seems to go away after some time. I'm still at Terminal build 1.12.10732.0 (updated yesterday), but I'm no longer having the issue, despite being absolutely positive I still had the issue previously even after updating to said Terminal build.

**Comment by zadjii-msft** [comment]
note to self: MSFT:38495673

We're still trying to track down a root cause. Issue does seem intermittent, and seems to go away with a reboot, if you are affected by this.

**Comment by zadjii-msft** [comment]
There are 4 additional reports in #12772. Collected notes:

> This issue only affects one tab at a time.
> The particular character is different every time.

> Same for me. Terminal version 1.12.10393.0 - I _think_ this started with the latest windows insider build (22581)
> Terminal becomes unresponsive when typing **any** character, typically returns to being responsive after 30-60s. (And freezes again on the next character typed).

> I see it in 1.13.10734.0. It's any character, and the freeze isn't just terminal input - the window is not responsive (no dragging, drop-down, etc.) as well.

>  I see the same window freeze even when I 'run as admin'.

> I get the freeze running as admin as well. Mine started on build 22581.100

> I just installed Terminal 1.10.2714 from the github release ([`v1.10.2714.0` (release)](https://github.com/microsoft/terminal/releases/tag/v1.10.2714.0)) and can confirm that the same freeze happens there. On Windows 11 build 22581.

> I can also verify that rebooting solved it (or at least made it go away for a while).
> 
> And also - I noticed what I thought was a different issue, but it disappeared after a reboot too which makes me suspect it has the same root cause and might help analyze: I wasn't able to record a trace with Windows-Performance-Recorder, neither to memory or disk. Upon 'Start', the recorder consistently threw a message box saying 'The requested resource is in use'. Gone after a reboot too.

**Comment by justinledwards** [comment]
Build 22581.200 (KB5013296) seems to have fixed it

**Comment by agentmerlot1412** [comment]
I'm facing the same issue on Terminal and Terminal Preview, but as a side note, it seems like this issue pops up in WSA applications and Microsoft Store too, although the severity of the issue in Store is much lower than that of Terminal and WSA.

**Comment by zadjii-msft** [comment]
Hey everybody - I believe there's a new flight that's out for Insiders, and the Input team has a sneaking suspicion that this may have been fixed in that build. Is anyone seeing this on **[22593](https://blogs.windows.com/windows-insider/2022/04/06/announcing-windows-11-insider-preview-build-22593/)**?

**Comment by asgeirn** [comment]
I no longer have this issue, currently on 22593.1 and Terminal versjon 1.13.10984.0

**Comment by agentmerlot1412** [comment]
Same

**Comment by zadjii-msft** [comment]
Awesome, I'm glad to hear it! Since this seems resolved, I'm gonna close this one out. Thanks everybody!

**Comment by jcwhitney** [comment]
still a problem on 22616.1 with feature pack 1000.22632.1000.0
cortana and Settings search not seeing any keyboard input.
Chrome / notepad etc all work

**Comment by zadjii-msft** [comment]
@jcwhitney That sounds like a different issue almost. Any chance you disabled the "Text Input Management Service"?
