### ISSUE TITLE
Visual Studio 2022 uses cmd instead of windows terminal

### ISSUE THREAD

**Issue by suntsu42** [microsoft/terminal#13047]
### Windows Terminal version

1.13.10984.0

### Windows build number

10.0.22000.0

### Steps to reproduce

I've configured windows terminal to be the default terminal:
![image](https://user-images.githubusercontent.com/1768336/167101141-1090f46b-6c60-448a-b4f9-34d93df2e978.png)

I've created a simple .net 6 console application in Visual Studio Professional 2022
![image](https://user-images.githubusercontent.com/1768336/167101187-e05ed0fb-a8c2-49e8-a140-3ff5779446cb.png)

When i debug this console application, its started in a cmd shell rather than in the windows terminal
![image](https://user-images.githubusercontent.com/1768336/167101313-5982a9f4-9968-4ae0-8152-d5e8f98abf83.png)

When i run **cmd** via "Windows-R", it does actually start the terminal (as expected). This means the windows terminal is set as default terminal for windows. 

Is there a specific settings in visual studio in order to force the use of the windows terminal?

### Expected Behavior

Visual studio starts the windows terminal when debugging a console application

### Actual Behavior

Visual studio starts the cmd terminal

**Comment by fortizfe** [comment]
Hello! 

Same problem here

**Comment by Paril** [comment]
Still an issue on `Version 17.3.0 Preview 2.0` - always launches with cmd, despite Terminal being the default app.

**Comment by rubo** [comment]
Same here but only with ASP.NET Core projects. Standard console apps or Azure Function apps run in Windows Terminal.

**Comment by zadjii-msft** [comment]
Hmm, I'm up to 17.3.0 Preview 2.0 now, and I'm still not seeing this, even with a `<Project Sdk="Microsoft.NET.Sdk.Web">` console app.

![image](https://user-images.githubusercontent.com/18356694/182210753-4470fa6d-4aa9-435a-8341-12830a07fa7b.png)

The default terminal detection has been pretty stable for a few OS release now. If there's some subset of VS projects that this does still repro for, best to report this directly at [Developer Community](https://developercommunity.visualstudio.com/search?entry=problem&space=8).

(spoiler alert: [looks like they've got a lot of issues with their handoff](https://developercommunity.visualstudio.com/search?entry=problem&space=8&q=default+terminal))

**Comment by rubo** [comment]
Fixed in Visual Studio v17.3.0

**Comment by suntsu42** [comment]
I'm now using Visual Studio v17.3.0 and it still doesn't open the windows terminal. 
![image](https://user-images.githubusercontent.com/1768336/184290400-5d592f59-f608-4d2d-a7ab-710896e9ba2d.png)
![image](https://user-images.githubusercontent.com/1768336/184290439-d1146612-e5c0-4259-8229-ca01268fe23d.png)

**Comment by MasterIPI** [comment]
> I'm now using Visual Studio v17.3.0 and it still doesn't open the windows terminal. ![image](https://user-images.githubusercontent.com/1768336/184290400-5d592f59-f608-4d2d-a7ab-710896e9ba2d.png) ![image](https://user-images.githubusercontent.com/1768336/184290439-d1146612-e5c0-4259-8229-ca01268fe23d.png)

Just found a work around for me, check your startup configurtion of the visual studio. If it runs as administrator - then it won't launch the terminal, remove checkbox in startup options from that option and it will launch console apps in the terminal.

**Comment by sineme** [comment]
Try changing _Windows Terminal > Settings > Default terminal application_
from _Let Windows decide_ to _Windows Terminal_.

**Comment by mayureshs** [comment]
Is there a way to launch VS2022 as administrator and still have the Terminal as the default option instead of the ConsoleApp?

**Comment by MaverickMartyn** [comment]
I too would like to know how to get that to work, since my workflow requires me to run VS as administrator so I can debug the IIS (w3wp.exe) process.
VS Version: 17.9.6.
Windows Terminal Version: 1.19.10821.0

**Comment by zadjii-msft** [comment]
We're more or less tracking that issue over in #10276. It's a platform limitation currently that elevated applications cannot use the default terminal handoff.

**Comment by Echostorm44** [comment]
Still not working for Admin (which is how many of us have to run it)  

![Image](https://github.com/user-attachments/assets/127f6cdc-4287-4dd8-b364-e8a8cf3e899a)
