### ISSUE TITLE
After quitting vim and resizing the wt, terminal still shows vim interface

### ISSUE THREAD

**Issue by leimath** [microsoft/terminal#13184]
### Windows Terminal version

Terminal (Unpackaged) Version: 1.13.220523001

### Windows build number

10.0.19044.0

### Other Software

Name        : vim
Description : A highly configurable text editor for efficiently creating and
              changing any kind of text. (tux build)
Version     : 8.2.5016

### Steps to reproduce

0. [Optional] Disable scrollbar in settings (There is a issue with scroll bar already. Disabling the scroll bar mitigates the issue.)
1. Start Windows Terminal again in a smaller window size (Columns - 83 * Rows - 31 for me). 
2.  Spam a bunch of commands/errors to create some text before vim is started.
3. Type `vim`.
4. Press `a`or `i` to get int insert mode. Spam a bunch of text in subsequent lines.
5. Make Windows Terminal maximized (`Maximize` button in top right corner) or full screen (`Alt` + `Enter`)
6. Quit vim with `:q!`
7. See the bottom of windows terminal
8. Write some commands to see more glitches happen!

Note: If exited vim with `:q!` before maximizing (Step: 5) then the entire screen text are in diagonals causing a rendering glitch when maximized after quitting vim. As shown below:

<img src="https://user-images.githubusercontent.com/96306150/170454160-be39a461-0c85-4e6f-b8e6-2dab05f363b3.png" width="650" height="379" />

* I can list the scroll bar issue later on.

### Expected Behavior

Should quit normally without causing any interference in the top shell.

### Actual Behavior

Glitches on entering commands post maximized resize. Vim lines in the shell. See the image attached here:

<img src="https://user-images.githubusercontent.com/96306150/170452814-a43bd240-83ed-44d2-b1f5-cd99f1b5d66b.png" width="650" height="379" />

Ignore the text errors above `vim`, they are just spam text.

**Comment by zadjii-msft** [comment]
I believe this is fixed in [1.14 Preview](https://github.com/microsoft/terminal/releases/tag/v1.14.1432.0), can you try that build out and confirm for me/?

**Comment by leimath** [comment]
> I believe this is fixed in [1.14 Preview](https://github.com/microsoft/terminal/releases/tag/v1.14.1432.0), can you try that build out and confirm for me/?

Not fixed as seen below. I can also replicate the issue mentioned in note as well in this preview version (Didn't add the image here however).

<img src="https://user-images.githubusercontent.com/96306150/170525312-e449977a-938e-4ad9-8821-e7d806c58afb.png" width="650" height="379" />

Terminal version: Windows Terminal Preview Version: 1.14.1432.0

Resizing it again gives this:

<img src="https://user-images.githubusercontent.com/96306150/170525776-511c8ce4-59c3-4868-b7bd-37309e977f4a.png" width="650" height="379" />

**Comment by Vidzhel** [comment]
You may try this, don't know if it'll help
https://github.com/microsoft/terminal/issues/1940#issuecomment-1159494480

**Comment by leimath** [comment]
> You may try this, don't know if it'll help [#1940 (comment)](https://github.com/microsoft/terminal/issues/1940#issuecomment-1159494480)

Nope, didn't help. I can still repro.
