### ISSUE TITLE
GUI windows created by PowerShell appear in the background the first time they're launched after a reboot

### ISSUE THREAD

**Issue by corbob** [microsoft/terminal#13514]
### Windows Terminal version

1.15.1862

### Windows build number

10.0.19044.0

### Other Software

PowerShell 7.2.5
Windows PowerShell 5.1

### Steps to reproduce

1. In either PowerShell or Windows PowerShell run `Get-Process | Out-GridView`
2. Observe that the window appears behind the Terminal
3. Run the command again
4. Observe that the window is now appearing in front of the Terminal

**note:** I have tried to launch `notepad.exe` one time, and it appeared in front, and after that all other windows also appeared in front. This behaviour also only occurs after a reboot, so to duplicate it again you need to reboot.

### Actual Behavior

![2022-07-15_13-24-43 (1)](https://user-images.githubusercontent.com/30301021/179306567-4cf944c2-2ff2-4d8b-85e4-65f1ba0a8323.gif)

**Comment by zadjii-msft** [comment]
> This behaviour also only occurs after a reboot, so to duplicate it again you need to reboot.

_wat_

That's crazy if that's true. Did you have the terminal set up to automatically launch on startup/? That might explain why we wouldn't have gotten a focus event. Theoretically, this should have been fixed by the pile of PRs linked to #2988, but they would require the terminal to get focused while it was the foreground window.

**Comment by corbob** [comment]
I don't have an update I can provide at the moment as I'm not near a computer, and I may not get a chance for a few days, but I don't want this to close just yet, so I'll leave a comment with my intentions to follow up by Tuesday or Wednesday.

**Comment by ajansveld** [comment]
I can confirm this behavior still exists in Terminal Preview 1.16.2523.0
