### ISSUE TITLE
Entering the Settings menu in fullscreen can become stuck due to disabled keybinds

### ISSUE THREAD

**Issue by raethkcj** [microsoft/terminal#14051]
### Windows Terminal version

1.14.2281.0

### Windows build number

10.0.19044.1889

### Steps to reproduce

Note: Keybinds listed are my own, I believe they're the defaults but I can't remember for sure.
1. Open Terminal
2. Enter fullscreen mode (Alt+Enter)
3. Open the Settings menu (Ctrl+,)
4. Attempt to leave the Settings menu via:
    - Ctrl+W (Close Tab keybind)
    - The 'Save' button
    - The 'Discard changes' button
    - Alt+Enter
    - Esc
5. Note that none of the above work and you are seemingly stuck

### Expected Behavior

There should be some obvious way of exiting the Settings menu, whether it's a GUI button, the user's chosen Close Tab key, or otherwise.

### Actual Behavior

There is no readily apparent way to leave the fullscreen Settings menu.

Here is a short video of me trying to do so: https://youtu.be/XFII1thF1Xc

Eventually I tried Ctrl+Tab and found out that this keybind works to change tabs while stuck this way. I could then get out of fullscreen mode while in a regular terminal tab, and then close the Settings tab.

The Close Pane keybind Ctrl+Shift+W also seems to work, but it's not obvious that the Settings menu is a Pane and not a Tab.

**Comment by zadjii-msft** [comment]
Huh, okay closeTab should totally work in the SUI. There's only so many actions that work there, but closeTab should too.

**Comment by Swinkid** [comment]
@raethkcj Can you try using F11 to escape? I've just tried to replicate your issue and was able to escape using the F11 key... unless you've remapped it maybe?

**Comment by raethkcj** [comment]
F11 does indeed work, but was not what I used to enter fullscreen mode. There's no intuitive reason for two keybinds for the exact same function to work differently.

**Comment by Swinkid** [comment]
> F11 does indeed work, but was not what I used to enter fullscreen mode. There's no intuitive reason for two keybinds for the exact same function to work differently.

 I totally agree. @zadjii-msft thoughts on how this can be changed? Willing to assist implementation....

**Comment by zadjii-msft** [comment]
Hmm. That's a good question. #10121 looks like where we hooked up the keybindings / actions to the settings UI. Maybe the closeTab handler checks to see if the selected tab is a `TerminalTab`, and the settings tab fails that...

**Comment by zadjii-msft** [comment]
> However, pressing Alt on settings page (fullscreen or not) freezes the UI because the program seems to go into infinite loop infinite loop

wat

That doesn't make sense

ah butts. 

in #15189 we should have added a `break` after the `focusedObject = _root.try_as();` line.

**Comment by michalnpl** [comment]
@zadjii-msft I tried adding the necessary breaks, and **Alt** no longer freezes the settings page, but **Alt+Enter** will not make it go fullscreen.

Separately, when you try F11 on the settings page to go full screen, there will be **Access violation reading location 0x0000000000000000**, but that's unrelated, and I already have a fix for that; I just need to file an issue and can submit a PR.

**Comment by zadjii-msft** [comment]
Oh there's also a crash on trying to closeTab from the SUI tab. From #15196. That's a easy fix though

**Comment by zadjii-msft** [comment]
After fixing that crash though, I can't repro the original bug (Close the settings tab via `closeTab` bound to <kbd>Ctrl+w</kbd>). I dunno where this was fixed, I dunno if we really need to bisect it though. Might have just been #15189.

**Comment by michalnpl** [comment]
I still can't close the tab with **ctrl+w** after fixing the crash because, in the main branch, there is no "ctrl+w" binding in **defaults.json**.

**Comment by zadjii-msft** [comment]
I mean, sure. I'm assuming OP added the closeTab binding themselves to their `settings.json`.

**Comment by zadjii-msft** [comment]
I'm gonna mark this one up as "we think it's already fixed in 1.18, we'll have OP double-check for us when that comes out". Thanks!

**Comment by zadjii-msft** [comment]
@raethkcj can you double-check if this is fixed for you in Terminal Preview v1.18/?

**Comment by raethkcj** [comment]
@zadjii-msft yep, I can confirm that in Terminal Preview 1.18.1462.0, adding and using Ctrl+W to close the Settings menu (fullscreen or not) is working!

Thanks for chasing this down, even if it was relatively minor!

**Comment by zadjii-msft** [comment]
Thanks for following up!
