### ISSUE TITLE
Malformed/Partially destroyed Standard output from Visual studio (& others)

### ISSUE THREAD

**Issue by ForgotMyCode** [microsoft/terminal#14512]
### Windows Terminal version

1.15.2875.0

### Windows build number

10.0.22000.1281

### Other Software

Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.4.2

### Steps to reproduce

1. In Windows Settings, Windows Terminal should be set as default terminal.
2. In Visual Studio, create new C++ project, with arbitrary name
3. In arbitrary named .cpp file, insert this sample code:
```
#include <iostream>

int main() {	
	for(int i = 0; i < 100; ++i) {
		std::cout << i << '\n';

	}
	return 0;
}
```
4. Set Release and x64 mode.
5. Click on "Start **Without** Debugging" button.
6. Close the terminal.
7. Click on "Start **Without** Debugging" button again.
8. Scroll up.

### Expected Behavior

I would expect to see previous output lines correctly when I scroll up.

### Actual Behavior

There is no output above the previously visible text, or the output is malformed.
![bug1](https://user-images.githubusercontent.com/79061723/206486691-0ea1e283-059e-4667-a28e-461c0b49277f.png)

_Note: Classic console works as expected in this scenario._

**Comment by zadjii-msft** [comment]
I could have sworn there was s dupe for this somewhere on the backlog...

Part of me worries that this is defterm specific. Like, the issue wouldn't repro in the Terminal if you launched the sample exe as `wt -- sample.exe`.


Does selecting the missing output with the mouse cause it to reappear/? If so, this could be #11214

**Comment by ForgotMyCode** [comment]
> Does selecting the missing output with the mouse cause it to reappear/?

No, it does not.

I can even select and copy paste everything and the text corresponds to what is visible in the terminal.

**Comment by DHowett** [comment]
This is pretty strange, and I can't reproduce it on VS 17.4.0. Can you share your `settings.json`? I must be missing something 🙂

**Comment by ForgotMyCode** [comment]
> Can you share your `settings.json`?

I figured it may be easier to reproduce if I just reset the settings to default (I erased everything in the settings.json and restarted the terminal). I am still able to reproduce the issue even with default settings. I any case here is my current settings.json:
[settings.zip](https://github.com/microsoft/terminal/files/10239678/settings.zip)

There is another little detail I have noticed: the scrollbar behaves pretty weird. Before I start scrolling, it is pretty large, as soon as I start scrolling, it gets way smaller:

Before scrolling:

![before](https://user-images.githubusercontent.com/79061723/207938295-6bf51f66-6d5b-4492-a62b-c045a4657811.png)

When I start scrolling:

![after](https://user-images.githubusercontent.com/79061723/207938355-4750b64a-2f20-4581-b558-a4c92019dafd.png)

**Comment by LucNanquette** [comment]
I can confirm, that I get exactly the same bug. First I thought it had to do with the 17.5 Preview version of Visual Studio. But even after rolling back from preview, the bug persisted.

**Comment by LucNanquette** [comment]
Not sure if this helps, but I found that if you leave the terminal window open and then just run the code again, without closing terminal window first, the issue doesn't appear. I can reproduce this all the time; first run = bugs, second run without closing terminal first = no issue.
So I guess that @ForgotMyCode is right by assuming it has something to do with the initialization of the terminal.
Also I can see, that at the first run, the tab name "Microsoft Visual Studio Debug Console" is followed by some long hex number code? (see screenshot below) This stays for a few seconds before it disappears. On the second run, without closing terminal first, this does not happen.

![image](https://user-images.githubusercontent.com/63251238/210162930-d0811ec3-9801-4dea-b23c-d1ef295bf970.png)

**Comment by LucNanquette** [comment]
But what really puzzles me is the fact, that I have been experiencing this issue first time a few weeks ago. So it could correspond with the release of v1.15.3466.0 2 weeks ago, but going back to v1.15.2875 doesn't solve the issue.
I don't know what I am missing... tried uninstalling/reinstalling, resetting the .json settings... nothing solved the issue yet, appart from switching from terminal to the Windows Console Host, there everything runs fine.

**Comment by zadjii-msft** [comment]
You know what, we play all sorts of silly games on "the first paint" for conpty. I bet there's something fucky going on there with outputting more than a whole screen full of text before ConPTY does it's first frame. 

I've been out of the codebase for two weeks, but that's where I'd starts. 

#14547 has basically the same repro and side effects. I bet they're the same.

**Comment by zadjii-msft** [comment]
UNBELEIVABLY[1], I can't repro this on a dev build, but I can on 1.17.3481.0 consistently

I bet this was fixed by the conpty changes in #14544. We don't have that commit in the selfhost build, but we do have it in main. 

I guess I could do my dilligence and bisect that commit. 

[1]: read as "_somehow totally believably_"

**Comment by zadjii-msft** [comment]
Uhg. I just needed to try more. This must be some strange race, cause I just got this in the current main (4c7879bfb). 

How are we gonna debug this? This is intermittent, timing-based, and occurs via defterm. Defterm means we can't use the debug tap. I'd reckon that attaching to VS would probably break the repro. 

My assumption from before is where I think I'll start:

> You know what, we play all sorts of silly games on "the first paint" for conpty. I bet there's something fucky going on there with outputting more than a whole screen full of text before ConPTY does it's first frame.

We've got two sets of symptoms here:
* Folks missing lines of output (but the newlines are all seemingly there). This creates blank lines of output in the Terminal
* Places where the entire line (including the newline) are missing. That results in just skipped numbers, but no blank lines:
  ![image](https://user-images.githubusercontent.com/18356694/212971412-9aa0e19c-1bbc-49a2-9d76-958d7c697a7f.png)

**Comment by zadjii-msft** [comment]
I put a test in `dev/migrie/b/14512-test-research`, but that all passed on `main`, so maybe this doesn't exactly have to do with the first frame optimizations. I don't think I'll get eyes on this before the 1.17 cutoff.

**Comment by daniel-bostan** [comment]
@zadjii-msft I have the same bug. A simple for loop to print 100 lines will show the first 70 empty (only the ones now in view of the final frame of the console mind you, running it at 120x30, if I increase the height it displays it _more_ correctly to a point).

![image](https://user-images.githubusercontent.com/114983496/232397523-26a926f1-26eb-44d8-afc3-244f81072332.png)

Only with the Windows Terminal, not reproducible choosing Windows Console Host as the default. Only happens at the beginning of the program, if I print 10,000 lines the bug affects the first few hundred.

Tried to reset settings.json to no avail. Reproducible in VStudio, CLion, Codeblocks with msvc, gcc and clang

**Comment by LucNanquette** [comment]
Yeah, still no fix in sight for this?

**Comment by zadjii-msft** [comment]
I _think_ this is fixed in #15298. I want to check that in to 1.18 and actually verify that this issue is resolved in 1.18, before committing that it closes this thread.

**Comment by daniel-bostan** [comment]
[v1.18.1421.0](https://github.com/microsoft/terminal/releases/tag/v1.18.1421.0) fixes the issue for me.

**Comment by whshields** [comment]
I'm running Visual Studio Community 17.6.2 and I'm getting the same bug. Anything I can add to my code besides Running without Debugging twice to stitch the issue?

**Comment by daniel-bostan** [comment]
> I'm running Visual Studio Community 17.6.2 and I'm getting the same bug. Anything I can add to my code besides Running without Debugging twice to stitch the issue?

Why not update the Terminal?

You can add a small delay, that's what I did to work around it. Like 50-60 ms or so before you start printing. Or you can switch to the Windows Console.

**Comment by zadjii-msft** [comment]
@whshields which Terminal version are you using? This is totally just a bug in the Terminal, regardless of VS version. 

I'm really tempted to just close this out now. We seemingly haven't gotten any reports of this in the last month, and it was a pretty noisy bug before that.

**Comment by ForgotMyCode** [comment]
In case it has any weight, I am still able to reproduce the bug even using the latest (stable) versions (Terminal 1.17.11461.0; VS 17.6.4), but I have noticed it is not consistently reproducible, probably depends on a machine's performance if not other factors.

**Comment by zadjii-msft** [comment]
That would make sense - the PR I think fixed this (#15298) is only in 1.18 (Preview) builds currently.

**Comment by ForgotMyCode** [comment]
@zadjii-msft I have tried the preview version, the issue seems to be fixed, well done! So, at least from my side this issue can be closed.

**Comment by SurfinBirdGames** [comment]
hi i have the same issue since i upgrade to win 11.
you can set the console to legacy mode to use the win 10 console.
RESTART YOUR PC!!!
the output is as expected 

![legacy](https://github.com/microsoft/terminal/assets/118484933/94f8c9e6-7997-40b7-b5b8-e427ad915ce2)

**Comment by ForgotMyCode** [comment]
Fixed in v1.18.

**Comment by whshields** [comment]
@ForgotMyCode , Sorry new to Visual Studio. How did you update the Terminal? I've installed the Terminal Preview from the Microsoft Store, but my debugger still appears to be on 1.17.11461.0. Thanks.
