### ISSUE TITLE
[1.18] Certain fonts will cause a renderer error (MesloLGM NF, Cascadia Code Nerd Font)

### ISSUE THREAD

**Issue by ffes** [microsoft/terminal#15416]
### Windows Terminal version

1.18.1421.0

### Windows build number

10.0.19045.2965

### Other Software

oh-my-posh v16.8.0
Ubuntu 22.04.02 LTS

### Steps to reproduce

- Make sure oh-my-posh is started automatically on startup
- Open a new tab
- Notice the render problems
- Press enters, type text
- Notice even more render problems
- Wait a while and see the renderer catch up

It seems impossible to create a screenshot with the snipping tool because when the focus on WT is lost, the renderer catches up immediately.

Tearing of a tab created an error the very first time, but couldn't reproduce it anymore.

### Actual Behavior

Various rendering issues

**Comment by lhecker** [comment]
I'm sorry for causing the issue - We only noticed it mere hours before publishing 1.18 and I already opened a PR to fix it: #15403. If you can and don't mind, it'd be great if you could use an alternative font just for a week, because it would help us find other potential bugs you might encounter. I personally for instance like using [Delugia](https://github.com/adam7/delugia-code). Otherwise, I hope we'll be able to ship a fix soon!

**Comment by zadjii-msft** [comment]
Collected notes from other threads:

Fixes:
* #15403
* #15427
* #15425


If you're experiencing this, you can
* Switch to another font temporarily. Delugia Code is apparently a bit better. 
* Manually disable the Atlas engine. You can do that in the `settings.json` like so:
  ```json
    "profiles":
    {
        "defaults":
        {
            "useAtlasEngine": false
            
  ```
  Or in the Settings UI:
  ![image](https://user-images.githubusercontent.com/2256941/240756131-c5ee4574-301f-486c-af26-cb9b0316674a.png)
  **You need to create new tabs after making this change, or restart the application**. Existing tabs will retain the text renderer they were created with.
---

@lhecker also built a Windows Terminal Preview version that integrates the previous 3 AtlasEngine bug fixes, 2 of which might be relevant here: #15403 and #15425. You can download it here: [blob.hecker.io/sharex/Microsoft.WindowsTerminalPreview_1.18.1443.0_8wekyb3d8bbwe.msixbundle](https://blob.hecker.io/sharex/Microsoft.WindowsTerminalPreview_1.18.1443.0_8wekyb3d8bbwe.msixbundle) I'm using my own personal domain because I don't want to expose my internal work addresses. However the file is properly cryptographically signed by Microsoft.

**Comment by withinboredom** [comment]
> We only noticed it mere hours before publishing 1.18

I'm not going to lie, I didn't even have the non-preview version installed and didn't even realize I was running the preview version. This thing is so rock solid for me, I wish I had it on my Linux machine.

Keep up the excellent work!

**Comment by ryan-ambit** [comment]
I can confirm the rendering error with nerd font v3 (Cascadia Cove Nerd Font Mono) when using neovim with nerd font v3 symbols.

After turning off `Atlas Engine`, the rendering is now normal!

**Comment by ffes** [comment]
Just tried v1.18.1462.0 and indeed the problem is fixed. Thanks a lot for fixing this so quickly.

**Comment by withinboredom** [comment]
@zadjii-msft -- still seeing some differences in rendering. This is correct:

<img width="848" alt="image" src="https://github.com/microsoft/terminal/assets/1883296/8ed13e3e-4d1b-44d9-b6b5-d92be88a14fe">


This is 1.18.1462.0

<img width="844" alt="image" src="https://github.com/microsoft/terminal/assets/1883296/98be6ad2-c428-4e76-9b86-ed041968eff7">

I can't figure out how to give you a simple reproduction, but the easiest would be to install oh-my-zsh and go through the powerlevel10k installation wizard which does a whole bunch of interesting things to the terminal.

**Comment by zadjii-msft** [comment]
@withinboredom Mind filing a new issue? That looks like a much more minor graphical error, vs the pretty substantial issue this thread was originally tracking. Thanks!

**Comment by withinboredom** [comment]
Will do, thanks for the fast response @zadjii-msft !
