### ISSUE TITLE
Terminal crashes when closing WT while modifying the color scheme colors

### ISSUE THREAD

**Issue by Jarung** [microsoft/terminal#15535]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.19045.2965

### Steps to reproduce

1. Open Windows Terminal Settings.
2. Choose the color schemes.
3. left click on a color scheme.
4. Select a color to change, When the color window pops up, click the Windows Terminal close button.

### Actual Behavior

Windows Terminal crashes and closes by itself

https://github.com/microsoft/terminal/assets/10348075/a0e1baa2-c228-48eb-8eba-7ddb12538cc8

**Comment by carlos-zamora** [comment]
@Jarung We think we fixed this for 1.18. Would you mind testing that version? It's in preview right now.

We'll continue to monitor this bug in the meantime.

**Comment by Jarung** [comment]
> @Jarung We think we fixed this for 1.18. Would you mind testing that version? It's in preview right now.我们认为我们在 1.18 中修复了这个问题。你介意测试那个版本吗？它目前处于预览状态。
> 
> We'll continue to monitor this bug in the meantime.在此期间，我们将继续监视此错误。

@carlos-zamora I'm sorry for not responding for a long time. I found that the problem still exists after verifying with 1.18.2822.0.
The dump file has been compressed and uploaded，please remove the zip suffix of the Z01-Z05 file before extracting it。

[WindowsTerminal.exe.10068.z05.zip](https://github.com/microsoft/terminal/files/13445612/WindowsTerminal.exe.10068.z05.zip)
[WindowsTerminal.exe.10068.zip](https://github.com/microsoft/terminal/files/13445613/WindowsTerminal.exe.10068.zip)


[WindowsTerminal.exe.10068.z01.zip](https://github.com/microsoft/terminal/files/13445607/WindowsTerminal.exe.10068.z01.zip)
[WindowsTerminal.exe.10068.z02.zip](https://github.com/microsoft/terminal/files/13445608/WindowsTerminal.exe.10068.z02.zip)
[WindowsTerminal.exe.10068.z03.zip](https://github.com/microsoft/terminal/files/13445609/WindowsTerminal.exe.10068.z03.zip)
[WindowsTerminal.exe.10068.z04.zip](https://github.com/microsoft/terminal/files/13445611/WindowsTerminal.exe.10068.z04.zip)

**Comment by Jarung** [comment]
Version 1.18.3181.0 has the same issue.
