### ISSUE TITLE
Window does not stay on top when "Always on top" is enabled

### ISSUE THREAD

**Issue by mjuopperi** [microsoft/terminal#17356]
### Windows Terminal version

1.19.11213.0

### Windows build number

Microsoft Windows NT 10.0.22631.0

### Steps to reproduce

1. Toggle "Always on top" on in settings and save
2. Keep using terminal
3. Eventually it stops staying on top

The only way to resume the "Always on top" behaviour is to disable and re-enable the settings with a save in between.

### Actual Behavior

Terminal window does not stay on top of other windows.

**Comment by zadjii-msft** [comment]
Okay, all the context:

* This was originally fixed in #8125
* But then I think I broke it in 1.18
  * Someone else once reported this in #16650




I bet this is a real regression. Should be easy enough to figure out how I messed this up in the process model refactor.

**Comment by mjuopperi** [comment]
@zadjii-msft is there some debug info I could grab from the application when the issue is happening?

**Comment by gerbuuu** [comment]
still broken in 1.22.10731.0
When you drag and drop the tab it start working

**Comment by elgarfo** [comment]
just experienced this in 1.23.13503.0

also thanks for the quick workaround gerbuuu
