### ISSUE TITLE
Cursor disappears when AtlasEngine and Software Rendering are used together

### ISSUE THREAD

**Issue by BoscoDomingo** [microsoft/terminal#17472]
### Windows Terminal version

1.20.11381.0

### Windows build number

Microsoft Windows NT 10.0.22631.0

### Steps to reproduce

Open a Terminal with AtlasEngine and Software Redering active together

### Expected Behavior

For the cursor to be shown

### Actual Behavior

Cursor is invisible

**Comment by lhecker** [comment]
"Works on my machine":

![image](https://github.com/microsoft/terminal/assets/2256941/835a07e8-d55b-4544-a7d6-966d2d365fad)

Is there anything else you can think of that may have broken it?

**Comment by PankajBhojwani** [comment]
@BoscoDomingo Can you repro this in [Windows Terminal Canary](https://github.com/microsoft/terminal#installing-windows-terminal-canary)? We suspect it might have been fixed there but just want to confirm!

**Comment by BoscoDomingo** [comment]
> @BoscoDomingo Can you repro this in [Windows Terminal Canary](https://github.com/microsoft/terminal#installing-windows-terminal-canary)? We suspect it might have been fixed there but just want to confirm!

@PankajBhojwani Copied my settings over and issue still happens. The moment I reverse the copying over, cursor is back. Here they are so you can take a look:

<details>
<summary>Settings</summary>

```json
 "profiles": 
    {
        "defaults": 
        {
            "antialiasingMode": "cleartype",
            "bellStyle": 
            [
                "audible",
                "taskbar"
            ],
            "colorScheme": "UltraViolent",
            "cursorShape": "bar",
            "elevate": true,
            "experimental.retroTerminalEffect": false,
            "font": 
            {
                "cellHeight": "1.3",
                "face": "JetBrainsMono NF",
                "size": 10.0
            },
            "intenseTextStyle": "all",
            "opacity": 82,
            "useAcrylic": true,
            "useAtlasEngine": true
        },
        "list": 
        [
            {
                "colorScheme": "Tango Dark",
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "hidden": false,
                "name": "Command Prompt",
                "startingDirectory": null
            },
            {
                "bellStyle": 
                [
                    "audible",
                    "taskbar"
                ],
                "colorScheme": "PaulMillr",
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "hidden": true,
                "name": "PowerShell 5",
                "startingDirectory": "%USERPROFILE%"
            },
            {
                "colorScheme": "One Half Dark",
                "font": 
                {
                    "face": "Consolasligaturizedv2 NF"
                },
                "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
                "hidden": false,
                "name": "PowerShell 7",
                "source": "Windows.Terminal.PowershellCore"
            },
            {
                "colorScheme": 
                {
                    "light": "UltraViolent"
                },
                "guid": "{51855cb2-8cce-5362-8f54-464b92b32386}",
                "hidden": false,
                "name": "Ubuntu 22.04LTS",
                "source": "CanonicalGroupLimited.Ubuntu_79rhkp1fndgsc"
            },
            {
                "adjustIndistinguishableColors": "always",
                "font": 
                {
                    "cellHeight": "1.3"
                },
                "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
                "hidden": true,
                "name": "Ubuntu",
                "source": "Windows.Terminal.Wsl"
            }
        ]
    },
    "schemes": 
    [
        {
            "background": "#191919",
            "black": "#191919",
            "blue": "#76D4FF",
            "brightBlack": "#191919",
            "brightBlue": "#63CEFC",
            "brightCyan": "#6CBFB5",
            "brightGreen": "#B7E876",
            "brightPurple": "#BA76E7",
            "brightRed": "#FF355B",
            "brightWhite": "#E1E3E9",
            "brightYellow": "#FFC251",
            "cursorColor": "#FFFFFF",
            "cyan": "#6CBFB5",
            "foreground": "#B3C9D7",
            "green": "#B7E876",
            "name": "Bright Lights",
            "purple": "#BA76E7",
            "red": "#FF355B",
            "selectionBackground": "#FFFFFF",
            "white": "#C2C8D7",
            "yellow": "#FFC251"
        },
        {
            "background": "#0C0C0C",
            "black": "#0C0C0C",
            "blue": "#0037DA",
            "brightBlack": "#767676",
            "brightBlue": "#3B78FF",
            "brightCyan": "#61D6D6",
            "brightGreen": "#16C60C",
            "brightPurple": "#B4009E",
            "brightRed": "#E74856",
            "brightWhite": "#F2F2F2",
            "brightYellow": "#F9F1A5",
            "cursorColor": "#FFFFFF",
            "cyan": "#3A96DD",
            "foreground": "#CCCCCC",
            "green": "#13A10E",
            "name": "Campbell",
            "purple": "#881798",
            "red": "#C50F1F",
            "selectionBackground": "#FFFFFF",
            "white": "#CCCCCC",
            "yellow": "#C19C00"
        },
        {
            "background": "#012456",
            "black": "#0C0C0C",
            "blue": "#0037DA",
            "brightBlack": "#767676",
            "brightBlue": "#3B78FF",
            "brightCyan": "#61D6D6",
            "brightGreen": "#16C60C",
            "brightPurple": "#B4009E",
            "brightRed": "#E74856",
            "brightWhite": "#F2F2F2",
            "brightYellow": "#F9F1A5",
            "cursorColor": "#FFFFFF",
            "cyan": "#3A96DD",
            "foreground": "#CCCCCC",
            "green": "#13A10E",
            "name": "Campbell Powershell",
            "purple": "#881798",
            "red": "#C50F1F",
            "selectionBackground": "#FFFFFF",
            "white": "#CCCCCC",
            "yellow": "#C19C00"
        },
        {
            "background": "#121212",
            "black": "#1B1D1E",
            "blue": "#66D9EF",
            "brightBlack": "#505354",
            "brightBlue": "#66D9EF",
            "brightCyan": "#A3BABF",
            "brightGreen": "#BEED5F",
            "brightPurple": "#9E6FFE",
            "brightRed": "#FF669D",
            "brightWhite": "#F8F8F2",
            "brightYellow": "#E6DB74",
            "cursorColor": "#FFFFFF",
            "cyan": "#5E7175",
            "foreground": "#A0A0A0",
            "green": "#A6E22E",
            "name": "Hardcore",
            "purple": "#9E6FFE",
            "red": "#F92672",
            "selectionBackground": "#FFFFFF",
            "white": "#CCCCC6",
            "yellow": "#FD971F"
        },
        {
            "background": "#121212",
            "black": "#121212",
            "blue": "#1080D0",
            "brightBlack": "#555555",
            "brightBlue": "#00AFFF",
            "brightCyan": "#51CEFF",
            "brightGreen": "#B1E05F",
            "brightPurple": "#AF87FF",
            "brightRed": "#F6669D",
            "brightWhite": "#FFFFFF",
            "brightYellow": "#FFF26D",
            "cursorColor": "#FFFFFF",
            "cyan": "#43A8D0",
            "foreground": "#BBBBBB",
            "green": "#98E123",
            "name": "Molokai",
            "purple": "#8700FF",
            "red": "#FA2573",
            "selectionBackground": "#FFFFFF",
            "white": "#BBBBBB",
            "yellow": "#DFD460"
        },
        {
            "background": "#0C0C0C",
            "black": "#1A1A1A",
            "blue": "#9D65FF",
            "brightBlack": "#625E4C",
            "brightBlue": "#9D65FF",
            "brightCyan": "#58D1EB",
            "brightGreen": "#98E024",
            "brightPurple": "#F4005F",
            "brightRed": "#F4005F",
            "brightWhite": "#F6F6EF",
            "brightYellow": "#E0D561",
            "cursorColor": "#FFFFFF",
            "cyan": "#58D1EB",
            "foreground": "#D9D9D9",
            "green": "#98E024",
            "name": "Monokai Remastered",
            "purple": "#F4005F",
            "red": "#F4005F",
            "selectionBackground": "#FFFFFF",
            "white": "#C4C5B5",
            "yellow": "#FD971F"
        },
        {
            "background": "#1A1A1A",
            "black": "#1A1A1A",
            "blue": "#9D65FF",
            "brightBlack": "#625E4C",
            "brightBlue": "#9D65FF",
            "brightCyan": "#58D1EB",
            "brightGreen": "#98E024",
            "brightPurple": "#F4005F",
            "brightRed": "#F4005F",
            "brightWhite": "#F6F6EF",
            "brightYellow": "#E0D561",
            "cursorColor": "#FFFFFF",
            "cyan": "#58D1EB",
            "foreground": "#C4C5B5",
            "green": "#98E024",
            "name": "Monokai Soda",
            "purple": "#F4005F",
            "red": "#F4005F",
            "selectionBackground": "#FFFFFF",
            "white": "#C4C5B5",
            "yellow": "#FA8419"
        },
        {
            "background": "#282C34",
            "black": "#282C34",
            "blue": "#61AFEF",
            "brightBlack": "#5A6374",
            "brightBlue": "#61AFEF",
            "brightCyan": "#56B6C2",
            "brightGreen": "#98C379",
            "brightPurple": "#C678DD",
            "brightRed": "#E06C75",
            "brightWhite": "#DCDFE4",
            "brightYellow": "#E5C07B",
            "cursorColor": "#FFFFFF",
            "cyan": "#56B6C2",
            "foreground": "#DCDFE4",
            "green": "#98C379",
            "name": "One Half Dark",
            "purple": "#C678DD",
            "red": "#E06C75",
            "selectionBackground": "#FFFFFF",
            "white": "#DCDFE4",
            "yellow": "#E5C07B"
        },
        {
            "background": "#FAFAFA",
            "black": "#383A42",
            "blue": "#0184BC",
            "brightBlack": "#4F525D",
            "brightBlue": "#61AFEF",
            "brightCyan": "#56B5C1",
            "brightGreen": "#98C379",
            "brightPurple": "#C577DD",
            "brightRed": "#DF6C75",
            "brightWhite": "#FFFFFF",
            "brightYellow": "#E4C07A",
            "cursorColor": "#4F525D",
            "cyan": "#0997B3",
            "foreground": "#383A42",
            "green": "#50A14F",
            "name": "One Half Light",
            "purple": "#A626A4",
            "red": "#E45649",
            "selectionBackground": "#FFFFFF",
            "white": "#FAFAFA",
            "yellow": "#C18301"
        },
        {
            "background": "#000000",
            "black": "#2A2A2A",
            "blue": "#396BD7",
            "brightBlack": "#666666",
            "brightBlue": "#709AED",
            "brightCyan": "#7ADFF2",
            "brightGreen": "#66FF66",
            "brightPurple": "#DB67E6",
            "brightRed": "#FF0080",
            "brightWhite": "#FFFFFF",
            "brightYellow": "#F3D64E",
            "cursorColor": "#FFFFFF",
            "cyan": "#66CCFF",
            "foreground": "#F2F2F2",
            "green": "#79FF0F",
            "name": "PaulMillr",
            "purple": "#B449BE",
            "red": "#FF0000",
            "selectionBackground": "#FFFFFF",
            "white": "#BBBBBB",
            "yellow": "#E7BF00"
        },
        {
            "background": "#212121",
            "black": "#212121",
            "blue": "#008EC4",
            "brightBlack": "#424242",
            "brightBlue": "#20BBFC",
            "brightCyan": "#4FB8CC",
            "brightGreen": "#5FD7AF",
            "brightPurple": "#6855DE",
            "brightRed": "#FB007A",
            "brightWhite": "#F1F1F1",
            "brightYellow": "#F3E430",
            "cursorColor": "#FFFFFF",
            "cyan": "#20A5BA",
            "foreground": "#F1F1F1",
            "green": "#10A778",
            "name": "PencilDark",
            "purple": "#523C79",
            "red": "#C30771",
            "selectionBackground": "#FFFFFF",
            "white": "#D9D9D9",
            "yellow": "#A89C14"
        },
        {
            "background": "#002B36",
            "black": "#002B36",
            "blue": "#268BD2",
            "brightBlack": "#073642",
            "brightBlue": "#839496",
            "brightCyan": "#93A1A1",
            "brightGreen": "#586E75",
            "brightPurple": "#6C71C4",
            "brightRed": "#CB4B16",
            "brightWhite": "#FDF6E3",
            "brightYellow": "#657B83",
            "cursorColor": "#FFFFFF",
            "cyan": "#2AA198",
            "foreground": "#839496",
            "green": "#859900",
            "name": "Solarized Dark",
            "purple": "#D33682",
            "red": "#DC322F",
            "selectionBackground": "#FFFFFF",
            "white": "#EEE8D5",
            "yellow": "#B58900"
        },
        {
            "background": "#FDF6E3",
            "black": "#002B36",
            "blue": "#268BD2",
            "brightBlack": "#073642",
            "brightBlue": "#839496",
            "brightCyan": "#93A1A1",
            "brightGreen": "#586E75",
            "brightPurple": "#6C71C4",
            "brightRed": "#CB4B16",
            "brightWhite": "#FDF6E3",
            "brightYellow": "#657B83",
            "cursorColor": "#002B36",
            "cyan": "#2AA198",
            "foreground": "#657B83",
            "green": "#859900",
            "name": "Solarized Light",
            "purple": "#D33682",
            "red": "#DC322F",
            "selectionBackground": "#FFFFFF",
            "white": "#EEE8D5",
            "yellow": "#B58900"
        },
        {
            "background": "#000000",
            "black": "#000000",
            "blue": "#3465A4",
            "brightBlack": "#555753",
            "brightBlue": "#729FCF",
            "brightCyan": "#34E2E2",
            "brightGreen": "#8AE234",
            "brightPurple": "#AD7FA8",
            "brightRed": "#EF2929",
            "brightWhite": "#EEEEEC",
            "brightYellow": "#FCE94F",
            "cursorColor": "#FFFFFF",
            "cyan": "#06989A",
            "foreground": "#D3D7CF",
            "green": "#4E9A06",
            "name": "Tango Dark",
            "purple": "#75507B",
            "red": "#CC0000",
            "selectionBackground": "#FFFFFF",
            "white": "#D3D7CF",
            "yellow": "#C4A000"
        },
        {
            "background": "#FFFFFF",
            "black": "#000000",
            "blue": "#3465A4",
            "brightBlack": "#555753",
            "brightBlue": "#729FCF",
            "brightCyan": "#34E2E2",
            "brightGreen": "#8AE234",
            "brightPurple": "#AD7FA8",
            "brightRed": "#EF2929",
            "brightWhite": "#EEEEEC",
            "brightYellow": "#FCE94F",
            "cursorColor": "#000000",
            "cyan": "#06989A",
            "foreground": "#555753",
            "green": "#4E9A06",
            "name": "Tango Light",
            "purple": "#75507B",
            "red": "#CC0000",
            "selectionBackground": "#FFFFFF",
            "white": "#D3D7CF",
            "yellow": "#C4A000"
        },
        {
            "background": "#1D1D26",
            "black": "#1D1D26",
            "blue": "#00CBFF",
            "brightBlack": "#636667",
            "brightBlue": "#00CBFF",
            "brightCyan": "#00D5D4",
            "brightGreen": "#00D364",
            "brightPurple": "#D783FF",
            "brightRed": "#FF2F92",
            "brightWhite": "#D5D6F3",
            "brightYellow": "#FFD479",
            "cursorColor": "#FFFFFF",
            "cyan": "#00CECA",
            "foreground": "#CBCBF0",
            "green": "#00D364",
            "name": "Tinacious Design (Dark)",
            "purple": "#CC66FF",
            "red": "#FF3399",
            "selectionBackground": "#FFFFFF",
            "white": "#CBCBF0",
            "yellow": "#FFCC66"
        },
        {
            "background": "#300A24",
            "black": "#171421",
            "blue": "#0037DA",
            "brightBlack": "#767676",
            "brightBlue": "#08458F",
            "brightCyan": "#2C9FB3",
            "brightGreen": "#26A269",
            "brightPurple": "#A347BA",
            "brightRed": "#C01C28",
            "brightWhite": "#F2F2F2",
            "brightYellow": "#A2734C",
            "cursorColor": "#FFFFFF",
            "cyan": "#3A96DD",
            "foreground": "#FFFFFF",
            "green": "#26A269",
            "name": "Ubuntu-22.04-ColorScheme",
            "purple": "#881798",
            "red": "#C21A23",
            "selectionBackground": "#FFFFFF",
            "white": "#CCCCCC",
            "yellow": "#A2734C"
        },
        {
            "background": "#300A24",
            "black": "#171421",
            "blue": "#0037DA",
            "brightBlack": "#767676",
            "brightBlue": "#08458F",
            "brightCyan": "#2C9FB3",
            "brightGreen": "#26A269",
            "brightPurple": "#A347BA",
            "brightRed": "#C01C28",
            "brightWhite": "#F2F2F2",
            "brightYellow": "#A2734C",
            "cursorColor": "#FFFFFF",
            "cyan": "#3A96DD",
            "foreground": "#FFFFFF",
            "green": "#26A269",
            "name": "Ubuntu-ColorScheme",
            "purple": "#881798",
            "red": "#C21A23",
            "selectionBackground": "#FFFFFF",
            "white": "#CCCCCC",
            "yellow": "#A2734C"
        },
        {
            "background": "#242728",
            "black": "#242728",
            "blue": "#71CAF2",
            "brightBlack": "#878A8C",
            "brightBlue": "#43F6FF",
            "brightCyan": "#69FCD3",
            "brightGreen": "#DEFF8C",
            "brightPurple": "#E681FF",
            "brightRed": "#FB58B4",
            "brightWhite": "#F9F9F5",
            "brightYellow": "#FFF393",
            "cursorColor": "#FFFFFF",
            "cyan": "#0EFFBB",
            "foreground": "#D1D1D1",
            "green": "#B6FF00",
            "name": "UltraViolent",
            "purple": "#D731FF",
            "red": "#FF0090",
            "selectionBackground": "#D1D1D1",
            "white": "#E1E1E1",
            "yellow": "#FFF727"
        },
        {
            "background": "#000000",
            "black": "#000000",
            "blue": "#000080",
            "brightBlack": "#808080",
            "brightBlue": "#0000FF",
            "brightCyan": "#00FFFF",
            "brightGreen": "#00FF00",
            "brightPurple": "#FF00FF",
            "brightRed": "#FF0000",
            "brightWhite": "#FFFFFF",
            "brightYellow": "#FFFF00",
            "cursorColor": "#FFFFFF",
            "cyan": "#008080",
            "foreground": "#C0C0C0",
            "green": "#008000",
            "name": "Vintage",
            "purple": "#800080",
            "red": "#800000",
            "selectionBackground": "#FFFFFF",
            "white": "#C0C0C0",
            "yellow": "#808000"
        },
        {
            "background": "#403257",
            "black": "#3D3D3D",
            "blue": "#6D77B3",
            "brightBlack": "#000000",
            "brightBlue": "#36F9F6",
            "brightCyan": "#F92AAD",
            "brightGreen": "#72F1B8",
            "brightPurple": "#E1ACFF",
            "brightRed": "#F88414",
            "brightWhite": "#FEFEFE",
            "brightYellow": "#FFF951",
            "cursorColor": "#FFFFFF",
            "cyan": "#F772E0",
            "foreground": "#F0EFF1",
            "green": "#72F1B8",
            "name": "synthwave-everything",
            "purple": "#C792EA",
            "red": "#F97E72",
            "selectionBackground": "#FFFFFF",
            "white": "#FEFEFE",
            "yellow": "#FEDE5D"
        }
    ],
    "tabWidthMode": "equal",
    "theme": "dark",
    "themes": [],
    "useAcrylicInTabRow": true,
```
</details>

**Comment by carlos-zamora** [comment]
Tried reproing on my machine by copying over the settings file. Had to make the following modifications:
- `profiles.defaults.font.face`: changed to `JetBrainsMono Nerd Font Mono` (installed [here](https://www.nerdfonts.com/font-downloads))
- comment out `profiles.list."PowerShell 7".font.face` because I don't have `Consolasligaturizedv2 NF` (but this one shouldn't affect anything)

On version 1.22.1831.0, which is the one the team bug bashed on 7/2. Opened a new tab with the default profile, which created a new "PowerShell 5" tab elevated. Double checked settings and "Use software rendering" wasn't enabled, so I had to add `"rendering.software": true,` to the settings.json.

After all that, still can't get a repro. I'm on a wide 4k monitor, if that affects anything. Let me know if I missed something.

Storing these notes here so we can take a look at this later and debug further. 😊

**Comment by BoscoDomingo** [comment]
> Tried reproing on my machine by copying over the settings file. Had to make the following modifications:
> 
>     * `profiles.defaults.font.face`: changed to `JetBrainsMono Nerd Font Mono` (installed [here](https://www.nerdfonts.com/font-downloads))
> 
>     * comment out `profiles.list."PowerShell 7".font.face` because I don't have `Consolasligaturizedv2 NF` (but this one shouldn't affect anything)
> 
> 
> On version 1.22.1831.0, which is the one the team bug bashed on 7/2. Opened a new tab with the default profile, which created a new "PowerShell 5" tab elevated. Double checked settings and "Use software rendering" wasn't enabled, so I had to add `"rendering.software": true,` to the settings.json.
> 
> After all that, still can't get a repro. I'm on a wide 4k monitor, if that affects anything. Let me know if I missed something.
> 
> Storing these notes here so we can take a look at this later and debug further. 😊

@carlos-zamora Tbf, I also have no clue what may be causing it. I have the exact same setup on my personal and work PCs, since I sync my settings to a private repo. Could it be something to do with GPU drivers/configuration? In the end, HW specs are really the only differences between the two.

I'll also go ahead and reinstall the Terminal app just in case, but I doubt that's an issue. I guess I'll have to live with slightly awkward glyphs from now on 🙃

**Comment by lhecker** [comment]
There's a good chance that something is broken with your graphics driver.

When you reduce the opacity, DWM (the desktop compositor) needs to blend the background behind the application, the contents of XAML and the terminal contents together. The problem is that XAML and the terminal contents are independent "swap chains" and I know that such a setup has caused some weird issues in the past. For instance, with modern Intel Xe GPUs resizing the window will randomly leave black rectangles on the screen.

What GPU are you using? Is there a newer driver from AMD/Intel/Nvidia available?

**Comment by BoscoDomingo** [comment]
@lhecker I have an RTX 3080 on my personal PC. I'll check for drivers ASAP, see if that fixes the issue
