### ISSUE TITLE
Ctrl+Break can leave the WSL shell in an unusable state

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#18425]
### Windows Terminal version

1.22.2702.0

### Windows build number

10.0.19045.5247

### Other Software

VIM 8.2.4919 (inside WSL)

### Steps to reproduce

1. Open the Settings, and set the *Profile termination behavior* to *Close only when process exits successfully*.
2. Start a WSL shell and run `vim`.
3. Enter `:set mouse=a` to enable mouse mode.
4. Press <kbd>Ctrl</kbd>+<kbd>Break</kbd> (possibly <kbd>Ctrl</kbd>+<kbd>ScrLock</kbd> depending on your keyboard).
5. When you see the `press Enter to restart` message, press <kbd>Enter</kbd>.
6. Once the shell restart, try clicking in the window to select some text.

### Expected Behavior

I'd expect mouse selection to work.

### Actual Behavior

When you click in the window, nothing can be selected, but a bunch of "random" characters get entered at the prompt. It seems that <kbd>Ctrl</kbd>+<kbd>Break</kbd> kills the session without giving the app a chance to exit gracefully, and then when we restart the session we don't reset any of the VT state either. As a result we're left with a mouse mode enabled which the shell wasn't expecting.

This mouse mode example was just the easiest to demonstrate, but you can see how it could be even more annoying if the app had enabled something like win32 input mode, or had selected a graphic character set.

**Comment by WhatsACloud** [comment]
Managed to reproduce the bug on version 1.21.3231.0 of windows terminal, and version 23H2 of windows 11.

Bug also appears to go away if you enter vim, do :set mouse = a, then exit vim normally using :q.

will investigate further later.

**Comment by j4james** [comment]
You can also just type `reset` to get the terminal back to a usable state, but ideally that should be something the terminal does itself when restarting a session. In fact it would be best if it did that before it even displayed the process exit message, because otherwise that can be unreadable. So maybe at the start of this method, or wherever this is called from.

https://github.com/microsoft/terminal/blob/25392ea6042242eceeb95cca29ca18784cf0ee7b/src/cascadia/TerminalConnection/ConptyConnection.cpp#L442-L453

It doesn't necessarily have to be be a hard reset, but at least a soft reset and then whatever additional modes are required to get the input back to normal.

**Comment by carlos-zamora** [comment]
Thanks for filing! `RestartConnection()` should fix this. Just a matter of calling the API on our end. 🙂

**Comment by WhatsACloud** [comment]
I'll fix this issue and submit a PR for it by this week.

**Comment by WhatsACloud** [comment]
@carlos-zamora I tried running RestartConnection() from the command palette but it doesn't appear to fix the issue.

What do you think of running the command "reset" when the user presses ctrl + break (but before the SIGKILL is sent), or after the user presses "enter" to restart?

**Comment by WhatsACloud** [comment]
Fixed this issue in this [PR](https://github.com/microsoft/terminal/pull/18437)
