### ISSUE TITLE
Bug Report - Jerky terminal

### ISSUE THREAD

**Issue by TayYuanGeng** [microsoft/terminal#1892]
# Environment

```
Microsoft Windows [Version 10.0.18362.207]
Windows Terminal version (if applicable): 0.2.1831.0
```

# Steps to reproduce

Open Windows Terminal,
Press Windows + Tab,
In the Windows Timeline,
Click on the Terminal,
When returning to Terminal,
The terminal seems to jerk for a fast moment and return to its original spot.

# Expected behavior

1. There should not be a jerky transition when returning back to Windows Terminal through Windows + Tab.

**Comment by widersky** [comment]
As far as I know (and see) it's Windows "UI" problem, not Terminal's one and yeah - should be fixed because sometimes is annoying as hell 😂

**Comment by zadjii-msft** [comment]
@TayYuanGeng You still seeing this? It's been a few years, so it's possible other OS updates might have just taken care of this for us. I'm not sure we really have any control over how the Terminal window behaves in the Win+Tab menu, but we can always forward a bug along to that team if needed.
