### ISSUE TITLE
Terminal window abends when elevated

### ISSUE THREAD

**Issue by noonand** [microsoft/terminal#19193]
### Windows Terminal version

1.22.11141.0

### Windows build number

23H2 (OS Build: 22631.5624)

### Other Software

None relevant

### Steps to reproduce

1. Start Terminal as an admin user
2. Open a Command Prompt tab
3. Open another PowerShell tab
4. Attempt to drag the new PowerShell tab so that it sits to the left of the Command Prompt tab
5. The Terminal window closes
6. Does not occur on a non-elevated Terminal window

### Expected Behavior

The PowerShell tab goes the left of the Command Prompt tab and you can continue to work

### Actual Behavior

Terminal window closes unexpectedly.

**Comment by DHowett** [comment]
Thanks for the report! This is a /duplicate of #15689; we attempt to _disable_ tab drag/drop when running as Admin because of this issue[^1] but it appears that that check is broken.

[^1]: (windows platform limitation resulting in a crash? say it ain't so)

**Comment by zadjii-msft** [comment]
Shoot that's the inverse of this issue.

**Comment by LeChat109** [comment]
in my case, when elevated, the terminal wont even open :

**Windows Terminal version**
1.22.12111.0

**Windows build number**
25H2 (OS Build: 26200.5733 ge_release Insider Dev, Windows feature pack 1000.26100.219.0)

**Other Software**
PowerShell 7.5.2 - Default profile
Windows terminal is configurated to launch elevated by default

**Steps to reproduce**
- i click the terminal shortcut in my taskbar
- it shows me an admin prompt
- i enter my password to accept it
- it shows me a 2nd admin prompt
- i enter my password again and accept it
- nothing happens

Does not occur on a non-elevated Terminal window
Does occur even when launching another profile (ex command prompt)
Does occur when launching any elevated profile via a non-elevated windows terminal window

**Expected Behavior**
The windows terminal should start correctly

Actual Behavior
2 admin prompts and then, no windows terminal window

ps:i tried reseting, uninstalling then re-installing the windows terminal and i also tried disabling any experimental options

[settings.json](https://github.com/user-attachments/files/21588511/settings.json)
[state.json](https://github.com/user-attachments/files/21588510/state.json)

**Comment by LeChat109** [comment]
This seems to be fixed in the latest version.
Can you confirm it @noonand ?

**Comment by noonand** [comment]
> This seems to be fixed in the latest version. Can you confirm it [@noonand](https://github.com/noonand) ?

Fixed might be a bit generous a term, what I now see in my version  (1.23.12811.0) is the behaviour that @DHowett mentions above whereby the drag and drop functionality is totally disabled. If this is the best that can be done I guess close the bug report.

**Comment by LeChat109** [comment]
Hi,
Just checked that, you are totally right and that's my bad.
I also agree that this isn't the bug fix we were awaiting for so the issue is still relevant.
