### ISSUE TITLE
UI is behaving weirdly while working on vim

### ISSUE THREAD

**Issue by AnikHasibul** [microsoft/terminal#1940]
While working on vim for editing files, it's behaving so weird.

Scrolling doesn't work, output seems messy. Line selector doesn't work properly. Terminal window vibrates so frequently.

**Comment by kshji** [comment]
after 1903 update also problem when using ex. reverse colors in terminal setup. (=usable setup for this kind of older user). When you change vim to the insert mode, line is reverse and looks that inserting is slow ?
Of course you can fix color problem to setup .vimrc line:
`highlight Normal ctermfg=black ctermbg=white`

but it's not usable when you use lot of hosts. Problem is in the WSL console

**Comment by DHowett-MSFT** [comment]
@AnikHasibul Is your report about Windows Terminal or Windows Console (the old one?)

**Comment by AnikHasibul** [comment]
Windows terminal. However, the issue has been fixed after removing NerdTree plugin on vim. I think it's an issue with NerdTree. Not with windows terminal.
You can close it. Or you can investigate further. Issue has been fixed on my end.
Cheers!

**Comment by aanari** [comment]
I'm still getting weird artifacts and misalined buffers in Vim 8.0 with the NERDTree plugin, but _only_ when the directory/file browser is open.

![image](https://user-images.githubusercontent.com/1236312/63204994-be0ec100-c052-11e9-8c27-2c971192a132.png)

I've never seen this issue before in any other terminal or operating system, and I've been using vim / NERDTree for almost 10 years now 🤔

**Comment by impguard** [comment]
^ Similar error for me as well. Strangely enough, it does seem reproduceable on a different machine, but I'm currently unable to figure out if there's a way to downgrade/change wsl versions to see if this is a wsl specific issue.

I've debugged it to the point that, for me, I can only reproduce it running neovim 0.5.1 on top of tmux. Neovim by itself does not seem to have this issue.

**Comment by Vidzhel** [comment]
If anyone is still stumbled across the issue, it can be solved by turning on `entire screen re-rendering`. Don't forget to save and relaunch terminal tab

!['Redraw entire screen when display updates' settings option](https://i.imgur.com/EpGkPea.jpeg)
