### ISSUE TITLE
Right-clicking on tab closes it

### ISSUE THREAD

**Issue by dmitrykobets-msft** [microsoft/terminal#19529]
### Windows Terminal version

1.23.12811.0

### Windows build number

10.0.22631.6060

### Steps to reproduce

Right-click on a tab in windows terminal preview
Previously this allowed me to rename / do actions with the tab.
Now it closes the tab.

### Expected Behavior

The tab should not get closed when right-clicking on it. Right-click is never a close behavior in any other Windows UI.

### Actual Behavior

The tab gets closed when right-clicking on it

**Comment by rijo7** [comment]
Hi! I’d love to work on this issue as my first contribution to Windows Terminal.

**Comment by zadjii-msft** [comment]
@rijo7 We don't typically assign out issues on this repo (unless it is to a core maintainer).

We'll review the PRs as we see them. Code Wins. 

How would you go about fixing this?

**Comment by zadjii-msft** [comment]
@dmitrykobets-msft Does this repro with [Terminal Canary](https://github.com/microsoft/terminal/discussions/16121)? This is most definitely not by design. But I can't repro this, so it'd be good to try and narrow down the root cause.

Did this regress recently for you/?

**Comment by rijo7** [comment]
I tested this on Windows Terminal Preview / Canary version 1.25.3101.0 on Windows 10 22H2.
Right-clicking on a tab now opens the context menu as expected, so this issue appears to be fixed in Canary.

**Comment by dmitrykobets-msft** [comment]
@zadjii-msft, @rijo7  I installed Canary (`1.25.3101.0`) and it does not repro.


The issue only repros on my Microsoft Devbox, windows version `10.0.22631.6060`, terminal version `1.23.12811.0`.
Video:
https://github.com/user-attachments/assets/645cdd5b-1304-4075-a771-5065d17c8f89

On my laptop`10.0.26100.4061`, same terminal version (`1.23.12811.0`) this never repros.
Video:
https://github.com/user-attachments/assets/40c62a79-6a45-4689-bdc8-0310a99dbd0c

In the above videos:
- left-click = yellow
<img width="54" height="64" alt="Image" src="https://github.com/user-attachments/assets/b2098fed-866b-4a8d-ac78-041476d6595f" />

- right-click = red
<img width="56" height="59" alt="Image" src="https://github.com/user-attachments/assets/fcd8d8a7-e2de-4c0a-b4b8-345e86b43678" />

- middle-click = cyan
<img width="61" height="69" alt="Image" src="https://github.com/user-attachments/assets/65e99b10-5a51-4548-9569-e9dfac86897c" />

Repro is when a red right-click results in a tab being closed.

**Comment by St-LF** [comment]
And it only happens on the first click. After the tab is closed, right-click on other tabs will open the menu as expected.

**Comment by lhecker** [comment]
This was fixed in #19273.

**Comment by lhecker** [comment]
I'll close this issue for now (for bookkeeping). As always, you can use [our Canary release](https://aka.ms/terminal-canary-installer) for the latest fixes.

**Comment by ragebiswas** [comment]
I still see this on  1.23.20211.0 :(

EDIT: Ah, I see this hasn't made it to 1.23.x yet.

**Comment by Eternal21** [comment]
For anyone still hitting this on the stable release (1.23), the fix from #19273 is included in Windows Terminal Preview (1.24). You can install it alongside your existing stable version with:

`winget install Microsoft.WindowsTerminal.Preview`

It runs side-by-side with the stable build, so you can switch back anytime. The fix should land in stable once 1.24 is promoted.

**Comment by 0x1881** [comment]
same problem

**Comment by ragebiswas** [comment]
I've been using terminal preview happily as my main driver.
