### ISSUE TITLE
Can't scroll or drag files over some areas with non 100% scaling

### ISSUE THREAD

**Issue by dsafa** [microsoft/terminal#2606]
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version (if applicable): built from master @ f4294b1

Any other software? N/A
```

# Steps to reproduce

1. Turn off the Windows setting `scroll inactive window when I hover over them`
2. Have terminal on monitor with scaling other than 100%
3. Have enough text to scroll
4. Focus terminal and scroll with mouse wheel

# Expected behavior

Terminal should scroll

# Actual behavior

Scrolling behavior is different depending on the mouse position. In some areas, it scrolls properly. In other regions, scrolling won't work.

- If scaling is 100%, then scrolling works properly. If scroll inactive window setting is on, then scrolling works properly.
- Same issue for both normal and non client window

![scroll-region](https://user-images.githubusercontent.com/7334282/63960813-28a50100-ca44-11e9-86f2-c50a889501bc.png)

Heres what I think is happening:

With `scroll inactive window` off, the wm_mousewheel messages are only be sent to current focused window (If i've read the docs correctly).
I think that the window that takes focus is not scaled properly so in some areas the mouse is 'outside' and won't receive the mouse wheel messages (maybe it needs to be focused and hovered?).
Terminal does have a couple windows (the host and the xaml island ones) but i'm not sure which one takes focus when terminal is active. I tried checking for wm_mousewheel in the window procs but I could not see the message being sent.
I have my suspicions that it's the top level window that is supposed to be receiving the messages because using Spy++, when I highlighted the top level window, its size also matched the area where scrolling works. But visually, everything seems to be scaled properly so I'm not too sure now.

**Comment by zadjii-msft** [comment]
@austin-lamb & @ocalvo might be interested in this

**Comment by DHowett-MSFT** [comment]
I just want to say we all really appreciate how robust this bug report is and how well you've investigated it.
Thanks!

**Comment by zadjii-msft** [comment]
Oh no, this is likely a platform bug. We've got a discussion with some folks on the XAML team to help investigate this, but I think this isn't going to make the 1.0 cut. 

This issue is now tracking the internal bugs MSFT:25518888 and MSFT:23625486

**Comment by zadjii-msft** [comment]
Also adding MSFT:35026617 to the list of internal tracking issues, since 23625486 was resolved, but didn't fix this.

**Comment by zadjii-msft** [comment]
Alrighty so MSFT:35026617 was fixed earlier this year, but unfortunately doesn't make the cut to service back to Windows 10. Alas 🤷. Anyways, this is fixed on the latest Windows 11 builds, so I'm gonna close this out, since there's nothing else for us to do here. Thanks!

**Comment by malcolm-bell** [comment]
Still not working.

https://github.com/microsoft/terminal/assets/104540921/6dd0b1e4-2d9e-4c1e-83fd-6e5d91e9e604
