### ISSUE TITLE
Bug Report: profile colorScheme not applied

### ISSUE THREAD

**Issue by Kizmar** [microsoft/terminal#3012]
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version (if applicable): 0.5.2681.0
Visual Studio Code version: 1.38.1
```

# Steps to reproduce
- Click on Settings from the menu (Ctrl+)
- For me this opens in Visual Studio Code
- Under existing profiles, add `"colorScheme": "<any_color_scheme>"`
- Save json file

# Expected behavior
- Changes colors to the scheme selected upon save of the json file
- Changing the `fontFace` & `fontSize` DOES change as expected (so it's somewhat working)

# Actual behavior
- Observe no change in the colors
- Restarted app after change, still no change in colors

## Other notes
I've reviewed [these docs](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md) and it seems pretty straight forward. I didn't see an issue stating that `colorSchemes` aren't working yet, but maybe I missed something.

I tried changing the profiles to one of the default included themes, and tried to add my own theme. Neither seemed to have any effect on the app colors when saved. Below is a current copy of my `profiles.json` file.

```
// To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation

{
	"$schema": "https://aka.ms/terminal-profiles-schema",

	"defaultProfile": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",

	"profiles": [{
			// Make changes here to the powershell.exe profile
			"guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
			"name": "Windows PowerShell",
			"commandline": "powershell.exe",
			"hidden": false,
			"colorScheme": "Afterglow",
			"fontFace": "Fire Code",
			"fontSize": 9
		},
		{
			// Make changes here to the cmd.exe profile
			"guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
			"name": "cmd",
			"commandline": "cmd.exe",
			"hidden": false,
			"colorScheme": "Afterglow"
		},
		{
			"guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
			"hidden": false,
			"name": "Azure Cloud Shell",
			"source": "Windows.Terminal.Azure",
			"colorScheme": "Afterglow"
		}
	],

	// Add custom color schemes to this array
	"schemes": [{
		"name": "Afterglow",
		"black": "#151515",
		"red": "#ac4142",
		"green": "#7e8e50",
		"yellow": "#e5b567",
		"blue": "#6c99bb",
		"purple": "#9f4e85",
		"cyan": "#7dd6cf",
		"white": "#d0d0d0",
		"brightBlack": "#505050",
		"brightRed": "#ac4142",
		"brightGreen": "#7e8e50",
		"brightYellow": "#e5b567",
		"brightBlue": "#6c99bb",
		"brightPurple": "#9f4e85",
		"brightCyan": "#7dd6cf",
		"brightWhite": "#f5f5f5",
		"background": "#212121",
		"foreground": "#d0d0d0"
	}],

	// Add any keybinding overrides to this array.
	// To unbind a default keybinding, set the command to "unbound"
	"keybindings": []
}
```

**Comment by zadjii-msft** [comment]
/dup #2883 #2936 #2978 #2943 #2925 #2902

**Comment by Kein** [comment]
I have a similar issue on 1.4.2
Powershell profile works perfectly with colorScheme
Command Line profile completely ignores any color schemes.

**Comment by zadjii-msft** [comment]
@Kein This issue was tracking a pretty specific bug that was fixed quite some time ago. Could you file a new issue to track your bug, and include your `settings.json` contents? Thanks!

**Comment by ericmassara** [comment]
Still happening with the new settings GUI in version 1.7, saving color theme doesn't apply

**Comment by zadjii-msft** [comment]
@ericmassara This particular issue (#3012) is like, 18 months old, and tracks a totally different root cause. Could you file a new issue, and include your `setting.json`? We're seeing some intermittent reports of settings not saving using the SUI, but it's been hard to identify a root cause. Having more data might help find the root cause here.

**Comment by thomas-haslwanter** [comment]
Same problem here: Windows Terminal Preview does NOT apply the chosen color schemes, neither to the "Command Prompt" nor to the "Windows Powershell"

**Comment by ezralazuardy** [comment]
Manually specifying `colorScheme` property in each profile inside `settings.json` works for me

![image](https://user-images.githubusercontent.com/24422019/122292143-dc2ffb80-cf1f-11eb-970e-7a04df7570a7.png)

**Comment by ap1969** [comment]
Thanks @ezralazuardy  - that worked for me too.

**Comment by shahzisme** [comment]
Like @ezralazuardy mentioned, alternatively, you can set a default instead to apply to all of them at once. 
![image](https://user-images.githubusercontent.com/1318063/124633667-173aa480-deb8-11eb-8529-19f532d427a4.png)

**Comment by systematicguy** [comment]
I would love to have a way of following the system theme also for pwsh, etc, not just the settings pane. My machine is set to switch themes when sunset or sunrise happens. I guess I will have to write some integration for auto-dark-mode that updates this setting. :)

**Comment by zadjii-msft** [comment]
@systematicguy You actually can do this in the Terminal already:

```json
"colorScheme":
{
    "light": "One Half Light",
    "dark": "One Half Dark",
},
```

[docs link](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#color-scheme)

**Comment by systematicguy** [comment]
> @systematicguy You actually can do this in the Terminal already:
> 
> ```json
> "colorScheme":
> {
>     "light": "One Half Light",
>     "dark": "One Half Dark",
> },
> ```
> 
> [docs link](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#color-scheme)

Perfect, works, thanks!

**Comment by dduyanhhoang** [comment]
> @systematicguy You actually can do this in the Terminal already:
> 
> ```json
> "colorScheme":
> {
>     "light": "One Half Light",
>     "dark": "One Half Dark",
> },
> ```
> 
> [docs link](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#color-scheme)

I have added this color scheme setting under 'profiles', 'profiles.defaults', 'profiles.list' but the color scheme does not adapt to the system color mode. Is there anything am I missing to apply this feature? Is the feature only apply to Windows Terminal Preview as mentioned in the given docs link?

**Comment by cosmoKenney** [comment]
I also have this problem, sort of. My "Developer Command Prompt for VS 2022" uses the "Solarized Light" color scheme set for "Command Prompt" in settings.json. the "defaults" section has "colorScheme" set to "Solarized Dark". So I am not sure what's goin on. My settings.json:

```
{
    "$help": "https://aka.ms/terminal-documentation",
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "actions": 
    [
        {
            "command": "paste",
            "keys": "ctrl+v"
        },
        {
            "command": 
            {
                "action": "copy",
                "singleLine": false
            },
            "keys": "ctrl+c"
        },
        {
            "command": "find",
            "keys": "ctrl+shift+f"
        },
        {
            "command": 
            {
                "action": "splitPane",
                "split": "auto",
                "splitMode": "duplicate"
            },
            "keys": "alt+shift+d"
        }
    ],
    "confirmCloseAllTabs": false,
    "copyFormatting": "none",
    "copyOnSelect": false,
    "defaultProfile": "{28cc5c55-7104-54c8-8d25-45a0195f3bea}",
    "initialRows": 45,
    "multiLinePasteWarning": false,
    "newTabMenu": 
    [
        {
            "type": "remainingProfiles"
        }
    ],
    "profiles": 
    {
        "defaults": 
        {
            "colorScheme": "Solarized Dark"
        },
        "list": 
        [
            {
                "colorScheme": "Campbell Powershell",
                "commandline": "%SystemRoot%\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "hidden": false,
                "name": "Windows PowerShell"
            },
            {
                "colorScheme": "Solarized Light",
                "commandline": "%SystemRoot%\\System32\\cmd.exe",
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "hidden": false,
                "name": "Command Prompt"
            },
            {
                "colorScheme": "One Half Light",
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            },
            {
                "colorScheme": "Solarized Dark",
                "font": 
                {
                    "face": "Consolas"
                },
                "guid": "{28cc5c55-7104-54c8-8d25-45a0195f3bea}",
                "hidden": false,
                "name": "Developer Command Prompt for VS 2022",
                "source": "Windows.Terminal.VisualStudio",
                "useAcrylic": true
            },
            {
                "colorScheme": "Solarized Dark",
                "guid": "{f61b85f9-b431-5808-9844-6699cf9626dc}",
                "hidden": false,
                "name": "Developer PowerShell for VS 2022",
                "source": "Windows.Terminal.VisualStudio"
            },
            {
                "colorScheme": "Solarized Dark",
                "guid": "{a59c4fac-874d-50ca-a8c2-72dc3ce8415a}",
                "hidden": true,
                "name": "Developer Command Prompt for VS 2019 (2)",
                "source": "Windows.Terminal.VisualStudio"
            },
            {
                "colorScheme": "Solarized Dark",
                "guid": "{8d135505-3550-5f8c-93a2-297b8d4a64ba}",
                "hidden": true,
                "name": "Developer PowerShell for VS 2019 (2)",
                "source": "Windows.Terminal.VisualStudio"
            },
            {
                "colorScheme": "Solarized Dark",
                "guid": "{f177095a-5492-5d54-9979-1a4dc0817adb}",
                "hidden": true,
                "name": "Developer Command Prompt for VS 2017",
                "source": "Windows.Terminal.VisualStudio"
            },
            {
                "colorScheme": "One Half Light",
                "guid": "{16208362-94fc-5b1f-a491-5b2624d5ab56}",
                "hidden": true,
                "name": "Visual Studio Debug Console",
                "source": "VSDebugConsole"
            }
        ]
    },
    "schemes": 
    [
        {
            "background": "#0C0C0C",
            "black": "#0C0C0C",
            "blue": "#0037DA",
            "brightBlack": "#767676",
            "brightBlue": "#3B78FF",
            "brightCyan": "#61D6D6",
            "brightGreen": "#16C60C",
            "brightPurple": "#B4009E",
            "brightRed": "#E74856",
            "brightWhite": "#F2F2F2",
            "brightYellow": "#F9F1A5",
            "cursorColor": "#FFFFFF",
            "cyan": "#3A96DD",
            "foreground": "#CCCCCC",
            "green": "#13A10E",
            "name": "Campbell",
            "purple": "#881798",
            "red": "#C50F1F",
            "selectionBackground": "#FFFFFF",
            "white": "#CCCCCC",
            "yellow": "#C19C00"
        },
        {
            "background": "#012456",
            "black": "#0C0C0C",
            "blue": "#0037DA",
            "brightBlack": "#767676",
            "brightBlue": "#3B78FF",
            "brightCyan": "#61D6D6",
            "brightGreen": "#16C60C",
            "brightPurple": "#B4009E",
            "brightRed": "#E74856",
            "brightWhite": "#F2F2F2",
            "brightYellow": "#F9F1A5",
            "cursorColor": "#FFFFFF",
            "cyan": "#3A96DD",
            "foreground": "#CCCCCC",
            "green": "#13A10E",
            "name": "Campbell Powershell",
            "purple": "#881798",
            "red": "#C50F1F",
            "selectionBackground": "#FFFFFF",
            "white": "#CCCCCC",
            "yellow": "#C19C00"
        },
        {
            "background": "#282C34",
            "black": "#282C34",
            "blue": "#61AFEF",
            "brightBlack": "#5A6374",
            "brightBlue": "#61AFEF",
            "brightCyan": "#56B6C2",
            "brightGreen": "#98C379",
            "brightPurple": "#C678DD",
            "brightRed": "#E06C75",
            "brightWhite": "#DCDFE4",
            "brightYellow": "#E5C07B",
            "cursorColor": "#FFFFFF",
            "cyan": "#56B6C2",
            "foreground": "#DCDFE4",
            "green": "#98C379",
            "name": "One Half Dark",
            "purple": "#C678DD",
            "red": "#E06C75",
            "selectionBackground": "#FFFFFF",
            "white": "#DCDFE4",
            "yellow": "#E5C07B"
        },
        {
            "background": "#FAFAFA",
            "black": "#383A42",
            "blue": "#0184BC",
            "brightBlack": "#4F525D",
            "brightBlue": "#61AFEF",
            "brightCyan": "#56B5C1",
            "brightGreen": "#98C379",
            "brightPurple": "#C577DD",
            "brightRed": "#DF6C75",
            "brightWhite": "#FFFFFF",
            "brightYellow": "#E4C07A",
            "cursorColor": "#4F525D",
            "cyan": "#0997B3",
            "foreground": "#383A42",
            "green": "#50A14F",
            "name": "One Half Light",
            "purple": "#A626A4",
            "red": "#E45649",
            "selectionBackground": "#FFFFFF",
            "white": "#FAFAFA",
            "yellow": "#C18301"
        },
        {
            "background": "#002B36",
            "black": "#002B36",
            "blue": "#268BD2",
            "brightBlack": "#073642",
            "brightBlue": "#839496",
            "brightCyan": "#93A1A1",
            "brightGreen": "#586E75",
            "brightPurple": "#6C71C4",
            "brightRed": "#CB4B16",
            "brightWhite": "#FDF6E3",
            "brightYellow": "#657B83",
            "cursorColor": "#FFFFFF",
            "cyan": "#2AA198",
            "foreground": "#839496",
            "green": "#859900",
            "name": "Solarized Dark",
            "purple": "#D33682",
            "red": "#DC322F",
            "selectionBackground": "#FFFFFF",
            "white": "#EEE8D5",
            "yellow": "#B58900"
        },
        {
            "background": "#FDF6E3",
            "black": "#002B36",
            "blue": "#268BD2",
            "brightBlack": "#073642",
            "brightBlue": "#839496",
            "brightCyan": "#93A1A1",
            "brightGreen": "#586E75",
            "brightPurple": "#6C71C4",
            "brightRed": "#CB4B16",
            "brightWhite": "#FDF6E3",
            "brightYellow": "#657B83",
            "cursorColor": "#002B36",
            "cyan": "#2AA198",
            "foreground": "#657B83",
            "green": "#859900",
            "name": "Solarized Light",
            "purple": "#D33682",
            "red": "#DC322F",
            "selectionBackground": "#FFFFFF",
            "white": "#EEE8D5",
            "yellow": "#B58900"
        },
        {
            "background": "#000000",
            "black": "#000000",
            "blue": "#3465A4",
            "brightBlack": "#555753",
            "brightBlue": "#729FCF",
            "brightCyan": "#34E2E2",
            "brightGreen": "#8AE234",
            "brightPurple": "#AD7FA8",
            "brightRed": "#EF2929",
            "brightWhite": "#EEEEEC",
            "brightYellow": "#FCE94F",
            "cursorColor": "#FFFFFF",
            "cyan": "#06989A",
            "foreground": "#D3D7CF",
            "green": "#4E9A06",
            "name": "Tango Dark",
            "purple": "#75507B",
            "red": "#CC0000",
            "selectionBackground": "#FFFFFF",
            "white": "#D3D7CF",
            "yellow": "#C4A000"
        },
        {
            "background": "#FFFFFF",
            "black": "#000000",
            "blue": "#3465A4",
            "brightBlack": "#555753",
            "brightBlue": "#729FCF",
            "brightCyan": "#34E2E2",
            "brightGreen": "#8AE234",
            "brightPurple": "#AD7FA8",
            "brightRed": "#EF2929",
            "brightWhite": "#EEEEEC",
            "brightYellow": "#FCE94F",
            "cursorColor": "#000000",
            "cyan": "#06989A",
            "foreground": "#555753",
            "green": "#4E9A06",
            "name": "Tango Light",
            "purple": "#75507B",
            "red": "#CC0000",
            "selectionBackground": "#FFFFFF",
            "white": "#D3D7CF",
            "yellow": "#C4A000"
        },
        {
            "background": "#000000",
            "black": "#000000",
            "blue": "#000080",
            "brightBlack": "#808080",
            "brightBlue": "#0000FF",
            "brightCyan": "#00FFFF",
            "brightGreen": "#00FF00",
            "brightPurple": "#FF00FF",
            "brightRed": "#FF0000",
            "brightWhite": "#FFFFFF",
            "brightYellow": "#FFFF00",
            "cursorColor": "#FFFFFF",
            "cyan": "#008080",
            "foreground": "#C0C0C0",
            "green": "#008000",
            "name": "Vintage",
            "purple": "#800080",
            "red": "#800000",
            "selectionBackground": "#FFFFFF",
            "white": "#C0C0C0",
            "yellow": "#808000"
        }
    ],
    "tabWidthMode": "titleLength",
    "theme": "system",
    "themes": 
    [
        {
            "name": "legacyDark",
            "tab": 
            {
                "background": null,
                "showCloseButton": "always",
                "unfocusedBackground": null
            },
            "window": 
            {
                "applicationTheme": "dark",
                "useMica": false
            }
        },
        {
            "name": "legacyLight",
            "tab": 
            {
                "background": null,
                "showCloseButton": "always",
                "unfocusedBackground": null
            },
            "window": 
            {
                "applicationTheme": "light",
                "useMica": false
            }
        },
        {
            "name": "legacySystem",
            "tab": 
            {
                "background": null,
                "showCloseButton": "always",
                "unfocusedBackground": null
            },
            "window": 
            {
                "applicationTheme": "system",
                "useMica": false
            }
        }
    ],
    "useAcrylicInTabRow": true,
    "windowingBehavior": "useAnyExisting"
}
```

**Comment by zadjii-msft** [comment]
Are you launching "Developer Command Prompt for VS 2022" from the Start Menu? Or the Terminal profile? 	If it's the former, then I reckon it's probably trying to profile match, and landing on the Command Prompt one (instead of the VS one)

This issue was originally tracking an entirely different root cause. I'd recommend filing a new thread.

**Comment by cosmoKenney** [comment]
> Are you launching "Developer Command Prompt for VS 2022" from the Start Menu? Or the Terminal profile? If it's the former, then I reckon it's probably trying to profile match, and landing on the Command Prompt one (instead of the VS one)
> 
> This issue was originally tracking an entirely different root cause. I'd recommend filing a new thread.

I launch it in different ways. There is a Start Menu shortcut which I use for one off terminals. But I also will start it from Visual Studio's Tools Menu, and from Visual Studio Task Runner. Not sure what you mean by "Terminal profile".
