### ISSUE TITLE
White border at the bottom of the window.

### ISSUE THREAD

**Issue by Borkason** [microsoft/terminal#3064]
# Environment

```none
Windows build number: 10.0.18995.0
Windows Terminal version (if applicable): 0.5.2762.0
```

# Steps to reproduce

Open Terminal app.

# Expected behavior

Should not show a white border on the bottom of the window.

# Actual behavior

Shows a 1 pixel thin white border on the bottom of the window.
![grafik](https://user-images.githubusercontent.com/2971735/66225365-8e864780-e6d8-11e9-943d-efa6741be223.png)

**Comment by carlos-zamora** [comment]
#1625? @DHowett-MSFT

**Comment by Androbots2001** [comment]
Can confirm the existence of the issue.

**Comment by ricardosantos9521** [comment]
It also shows a 1 pixel thin white border on the left side of the window. (build 19008)

Screen Resolution: 2256x1504, Scale: 125%:
![image](https://user-images.githubusercontent.com/20097801/67385357-e521cb80-f58a-11e9-9975-87b73e28dcd6.png)

Screen Resolution: 1920x1080, Scale: 100%:
![image](https://user-images.githubusercontent.com/20097801/67385610-4d70ad00-f58b-11e9-8d77-60e0ada0e3d3.png)

**Comment by DHowett-MSFT** [comment]
Chatted with the DWM team, who owns the API we're using to control our non-client drawing. They've got a solution for us, but it'll take some time to implement.
I'm tagging this into #1625.

**Comment by zadjii-msft** [comment]
(We think that this is going to be closely related to a bucket of things, #3136 #1859 #3064 #1307)

**Comment by Arush-Agarampur** [comment]
@DHowett-MSFT In some of my projects, I need to use `DwmExtendFrameIntoClientArea` to get a window shadow. But I make my main window layered, and make the color key for the window frame transparent. I think this will solve the issue:

`SetLayeredWindowAttributes(_window.get(), RGB(255, 0, 255), 0, LWA_COLORKEY);`

So it would look like this:

`    WINRT_VERIFY(CreateWindowEx(WS_EX_LAYERED,
                                wc.lpszClassName,
                                L"Windows Terminal",
                                WS_OVERLAPPEDWINDOW,
                                CW_USEDEFAULT,
                                CW_USEDEFAULT,
                                CW_USEDEFAULT,
                                CW_USEDEFAULT,
                                nullptr,
                                nullptr,
                                wc.hInstance,
                                this));
    SetLayeredWindowAttributes(_window.get(), RGB(255, 0, 255), 0, LWA_COLORKEY);`

Plus, you won't see the white lines at the top and bottom when resizing the window anymore.

**Comment by DHowett-MSFT** [comment]
@Arush-Agarampur Thanks! @greg904 actually has a comprehensive fix for this in progress in #3394.

**Comment by Arush-Agarampur** [comment]
Ahh OK, sorry I didn't see that. First time contributing to a huge project like this... 😅

**Comment by Borkason** [comment]
That made the issue 4 times worse as you now have 4 white borders: top left right and bottom 😂

![grafik](https://user-images.githubusercontent.com/2971735/69682542-01e17f80-10b2-11ea-8879-6aa458c467f6.png)

**Comment by DHowett-MSFT** [comment]
You're going to hate to hear this, but it's actually "by design" -- there's no official way for an application to opt in to match the shell's "dark theme" :frown:. If we trespass on those 1px borders, DWM will give up on us and force us to draw every pixel of our application. We've seen what lies at the end of that road.

**Comment by saschanaz** [comment]
You're going to hate to hear this (with all of your effort 🙏), but could we roll it back to affect only the bottom border? 🤔

**Comment by Arush-Agarampur** [comment]
I don't want to come across as pushy, but I think the best idea is to fall back to the bottom border, and use the layered window attribute I commented earlier. It hides it perfectly, also while resizing.

**Comment by DHowett-MSFT** [comment]
I appreciate your input. On the balance, though: the border pull request fixed at least seven different issues (#3064, #1307, #3136, #1897, #3222, #1859, #2268; this list does not count all the ones we later realized were caused by the same thing).
I'm willing to take a one-or-two-release regression in how terminal looks--at least until we can get it ironed out--in the name of improving our project's health.

I know that it's possible to get this right (Firefox manages it, for example), but I'd rather move forward and look for the _right_ solution than move backward and settle on the pretty bad solution we had.

**Comment by DHowett-MSFT** [comment]
Continuing discussion at #3425. We've figured out how to suppress the borders without using a private API. 😁

**Comment by Piroro-hs** [comment]
It still shows a 1 pixel thin white border on the left of **unfocused** window in some cases. In my case, it only shows when the screen scale is 125% and disappears after window is resized.

launched
![before](https://user-images.githubusercontent.com/22536104/70859601-c40da380-1f59-11ea-9f38-4cbdf6ba713f.JPG)

resized
![after](https://user-images.githubusercontent.com/22536104/70859612-f7e8c900-1f59-11ea-9f8e-0c0bb9b50b97.JPG)

Windows 10 18362.476
Windows Terminal 0.7.3451.0
