### ISSUE TITLE
Copying content inside About dialog crashes the terminal

### ISSUE THREAD

**Issue by skyline75489** [microsoft/terminal#4260]
# Environment

```none
Windows build number: 10.0.18363.535
Windows Terminal version (if applicable): Both on 0.7.3451.0 and current master

Any other software?
```

# Steps to reproduce

I'm trying to copy the version number inside About dialog. 

![批注 2020-01-16 225406](https://user-images.githubusercontent.com/4710575/72535351-5f749a00-38b3-11ea-8c01-62d3bf587551.png)

# Expected behavior

It works.

# Actual behavior

The terminal freezeed and crashed.

**Comment by skyline75489** [comment]
Current master is 6d6fb7f69058b78af0c77e376bed7228ad9eb41f.

**Comment by rioshin** [comment]
worked at least for me on the current version available through Store (0.8.10091.0)

**Comment by skyline75489** [comment]
Perhaps it's because of  system settings of something. I recall this used to be working but now it’s now. I’ll take a look wha I have time.

**Comment by skyline75489** [comment]
The crash is inside `Windows.UI.Xaml`. If I'm the only one having this, maybe it's because I got something wrong inside my laptop's environment.

**Comment by DHowett-MSFT** [comment]
I'm pulling triage but leaving needs-repro since we don't have a local repro. Thanks for the report!

**Comment by Toxic-Cat** [comment]
Windows version 18363.720, Windows Terminal version 0.10.761.0, still have the same issue. The system language is traditional Chinese(Taiwan). Sometimes need to click 'Copy' multiple time to trigger the crash.

**Comment by DHowett-MSFT** [comment]
I really tried with this one. I set my system language to Chinese, installed 0.10.761.0 directly from our releases page, and copied the contents of the about dialog about 40 times.

I just can't reproduce this. 😦

**Comment by skyline75489** [comment]
Yeah I'm having a hard time trying to reproduce it on my other laptop with 0.10.761.0. Even if I could reproduce it when I first reported this issue, it crashed somewhere deep inside `Windows.UI.Xaml`. I think we should leave it here, to see if there's more people having this issue.

**Comment by tamlin-mike** [comment]
Wasn't there a race in .NET FX discovered just the last few months? I don't know if the fix has been pushed to GA yet, but a dev machine might have more up-to-date binaries. That could explain both the difficulties to repro, and that it's deep inside some obscure asynch code handling XAML.

Just an idea.

**Comment by Toxic-Cat** [comment]
Just tried 0.10.781.0, still crashed on the first try. But after the first crash, I can copy the string normally without any crashes.

Faulting application name: WindowsTerminal.exe, version: 0.10.2003.18001, time stamp: 0x5e72d01a
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.18362.657, time stamp: 0xda02d3eb
Exception code: 0xc000027b
Fault offset: 0x0000000000712ec0
Faulting process id: 0x28f4
Faulting application start time: 0x01d5feeabc103103
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.10.781.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: b0ce9b3d-1dd8-461a-80b6-931e84243c85
Faulting package full name: Microsoft.WindowsTerminal_0.10.781.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

**Comment by skyline75489** [comment]
I think this no longer happens to me since I first opened this. And no one really reports similar issues for a very long time. I'll just close this for now.
