### ISSUE TITLE
Closing a tab doesn't terminate its associated process(es)

### ISSUE THREAD

**Issue by 0xabu** [microsoft/terminal#541]
When I close a tab (either via Ctrl-W or the close gadget), the underlying processes don't seem to be terminated. For example, this is what task manager shows if I've opened a few tabs and closed them:
![image](https://user-images.githubusercontent.com/13037682/57335805-a4b3bb80-70d8-11e9-9b2e-d2ade13ff9a6.png)
At the time I took this screenshot, there was only a single tab open.

* Your Windows build number:  18362

**Comment by DHowett-MSFT** [comment]
We could probably do with some job objects, and we definitely have a handle leak. Thanks for the report!

________________________________

**Comment by shuffle2** [comment]
Was just making new issue, but noticed this one.

# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.145]
Windows Terminal version (if applicable): 880272c7483a3bb6893dbec3725d0eb7375ab78a
```

# Steps to reproduce

Watch WindowsTerminal in procexp or something. Open and close tabs. Spawned processes are never killed until WindowsTerminal.exe is.

# Expected behavior

The code attempts to close spawned processes with tabs, but there are some refcount leaks on a `shared_ptr`.

# Actual behavior

Reference of newly created tab is given to 2 lambdas, which never die. It seems the API gives back a handle which you're supposed to use to remove the callback, which isn't currently done.
https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/App.cpp#L765
https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/App.cpp#L786

**Comment by DHowett-MSFT** [comment]
There's also some process isolation issues that result in console hosts sticking around after WT exits; #970 seeks to fix some of that.

**Comment by zadjii-msft** [comment]
@shuffle2 god find on those lines. I think I touched those in #825, but this issue will be helpful to make sure that those are fixed correctly.

**Comment by zadjii-msft** [comment]
Hey this was fixed in #541! Hooray!

Its also related to #745

**Comment by ms-xy** [comment]
I want to report that this is still an issue. It is impossible to terminate a misbehaving child process without terminating the terminal in the process.

Example situation: I start a wildfly server. After a while it becomes unresponsive. I close the tab, but the process lingers and is not terminated, blocking ports. If I try to end the process via task manager, it also terminates the parent process, effectively closing all my other tabs. Which in turn renders the tab feature pretty much useless.

**Comment by zadjii-msft** [comment]
@ms-xy This was a bug with a pretty specific root cause more than two years ago now - if you're seeing something similar, it's likely a new bug entirely. Mind filing a new issue? Knowing more about your exact setup might help debug & root-cause what you're seeing.
