### ISSUE TITLE
A11y_Windows Terminal_About_Screen Reader: Screen Reader is not reading the name of the dialogue box immediately when the dialogue box is opened

### ISSUE THREAD

**Issue by SpandanaPaladi** [microsoft/terminal#5419]
#A11y_WindowsTerminal; #WindowsTerminal; #A11yMAS; #A11yTCS; #DesktopApp; #Win10; #C+E-H; #ScreenReader; #Narrator; #A11ySev3; #MAS1.3.1

[Check out Accessibility Insights!](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-shcha1%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458847087032&sdata=uWx6cTEfazn%2BoCV3cL1iYB4KN%2BuXQ/MTlmOVec%2BZgKc%3D&reserved=0) - Identify accessibility bugs before check-in and make bug fixing faster and easier

**Repro steps:**

1. Turn on screen reader
2. Hit the URL ""aka.ms/terminal"" and install ""Windows terminal (Preview)"" application
3. Open ""Windows terminal (Preview)"" application
4. Tab to "Dropdown" control and press enter or use "Ctrl + Shift + Space"
5. Tab till "About" and press enter
6. Verify whether the "About" dialogue box is read immediately when the "About" dialogue box is opened

**Actual Result:**
Narrator is not reading the name of the dialogue box immediately when the "about" dialogue box is opened

**Expected Result:​**
Narrator should read the name of the dialogue box immediately when the "about" dialogue box is opened

**User Impact:​**
Screen Reader users will face difficulty if the name of the dialogue box is not read immediately when the "About" dialogue is opened because they don't understand what they opened 

**MAS Reference:​**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}

[Bug_Narrator not reading dialogue box name immediately after opening the pop up.pptx](https://github.com/microsoft/terminal/files/4502445/Bug_Narrator.not.reading.dialogue.box.name.immediately.after.opening.the.pop.up.pptx)

[Bug_NVDA not reading dialogue box name immediately after pop up is opened.pptx](https://github.com/microsoft/terminal/files/4502484/Bug_NVDA.not.reading.dialogue.box.name.immediately.after.pop.up.is.opened.pptx)

**Comment by carlos-zamora** [comment]
Verified that this was fixed sometime between 0.10 and 0.11. Tagging appropriately.

**Comment by Amulya-95** [comment]
Regressed the bug in latest environment. The issue is partially fixed, narrator is reading the 'About' dialog name when it is opened. But, NVDA is not reading the dialog name.
Please find the attachments for reference.

**Attachments:**
[[Fixed]Bug 5419_Narrator is reading 'About' dialog name.pptx](https://github.com/microsoft/terminal/files/4627873/Fixed.Bug.5419_Narrator.is.reading.About.dialog.name.pptx)

[[Not Fixed]Bug 5419_NVDA is not reading 'About' dialog name.pptx](https://github.com/microsoft/terminal/files/4627933/Not.Fixed.Bug.5419_NVDA.is.not.reading.About.dialog.name.pptx)

**Comment by carlos-zamora** [comment]
We're not doing anything special here. These are standard `ContentDialog` from WinUI. @DHowett-MSFT any suggestions on next steps here?

**Comment by DHowett** [comment]
This may be related to #5623.

**Comment by cinnamon-msft** [comment]
Should the Resolution-Fix-Available tag be removed?

**Comment by Amulya-95** [comment]
@carlos-zamora, @cinnamon-msft  Could you please confirm whether the issue is external to NVDA.

If it is external to NVDA, please provide Sample App so that we can log external bug to NVDA team and close this bud since it is working with Narrator.

**Comment by carlos-zamora** [comment]
Performed some further investigation. Turns out that this is _not_ an issue with NVDA, but rather an issue with XAML Islands. A ContentDialog with a hyperlink is not presented properly via screen readers.

This is an external bug being tracked by https://github.com/microsoft/microsoft-ui-xaml/issues/2681.

@Amulya-95 is this sufficient for us to close the bug, since there's nothing we can do but wait for a fix on their end?

**Comment by Amulya-95** [comment]
@carlos-zamora Current bug can not be closed.
As per [C&AI External bug process](https://microsoft.sharepoint.com/teams/ceacc/SitePages/External-Bug-process.aspx) we will take action on the current bug, once the external bug is fixed and fixes are available in the testing environment.

**Comment by Amulya-95** [comment]
@cinnamon-msft  SLA cannot be changed. However, if required you can follow [Exclusion Process](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoft.sharepoint.com%2Fteams%2Fceacc%2FSitePages%2FExternal-Bug-process.aspx&data=02%7C01%7Cv-amus%40microsoft.com%7Cdf5e765e185843978c7c08d81207b497%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637279171887052552&sdata=y4ihErJhFRhybxx4BdvBI%2BH%2B9sJmlSsmP7DrJB3MlfA%3D&reserved=0).

**Comment by cinnamon-msft** [comment]
Per the exclusion process:

**Importance of Experience**
Low impact. The title of the dialog box is not automatically read out loud upon opening.

**Quality of Experience**
Low impact. The user can still tab to the dialog box title in order for it to be read out loud by a screen reader.

AAT Conformance Doc listed under "Windows Terminal - Win32": https://cloudblogs.microsoft.com/industry-blog/government/2018/09/11/accessibility-conformance-reports/

**Comment by Amulya-95** [comment]
@Alexandria-R as per the above comments could you please take appropriate action on this bug.
Thanks!

**Comment by Alexandria-R** [comment]
We need written acceptance of the bug from the external team before this can be processed for exclusion.

**Comment by cinnamon-msft** [comment]
@Alexandria-R Do the comments on this filed bug on their repository count as written acceptance, or is there a formal process we need to follow? https://github.com/microsoft/microsoft-ui-xaml/issues/2681

**Comment by Alexandria-R** [comment]
That should do! Please attend office hours to discuss the bug.

**Comment by zadjii-msft** [comment]
~Possibly related to https://github.com/microsoft/microsoft-ui-xaml/issues/5909 or #11295.~

Nevermind. This looks like it was fixed at some point in the past. Maybe MUX 2.8?
