### ISSUE TITLE
Cursor does not blink

### ISSUE THREAD

**Issue by casperx** [microsoft/Terminal#665]
* Your Windows build number: Microsoft Windows [Version 10.0.18362.86]
* What you're doing and what's happening:
Run Windows Terminal (Preview) and it started with cmd.exe. The cursor is not blink as in original console.
* What's wrong / what should be happening instead:
The cursor does not blink.

**Comment by zadjii-msft** [comment]
This is a known issue at the moment - conhost has a timer for specifically blinking the cursor, but there's no such timer in the Terminal currently.

I don't _think_ this would be terribly difficult for someone to dig their hands into.

**Comment by dkter** [comment]
I have a blinking cursor working. Right now it just blinks all the time, but it should probably stop in certain circumstances, such as when typing or moving the cursor. Am I missing anything?

**Comment by dkter** [comment]
I've implemented the following behavior:
- When the window is unfocused, the cursor goes away. This is consistent with both conhost and PowerShell, however some terminals like ConEmu leave the cursor on when the window is unfocused.
- When a key is pressed, the cursor is shown and the timer is restarted. This is what ConEmu does. conhost is similar, but it seems to just show the cursor and not restart the timer, which makes it a little jitterier when testing both methods side by side. I still can't figure out what PowerShell is doing. Either way, I prefer this behavior and haven't noticed any significant performance impact in my testing.

Any other edge cases to cover?

**Comment by oising** [comment]
> Edit: The PowerShell and cmd hosts seem to have different behaviour, and I can't figure out what the PowerShell host is doing (it seems to blink the cursor really fast when a key is held down?)

Both powershell and cmd should have the same behaviour as they share the same host: conhost. That said, powershell is managed code and cmd is native, so you're probably seeing more jitter and flickering due to the overhead of CLR interop.

**Comment by dkter** [comment]
Here's a comparison between cmd, PowerShell and Windows Terminal, rapidly pressing `k` and then holding down `j`. Powershell's behaviour still seems pretty strange, but then again most people don't pay attention to cursor blinkage as much as I have been in the past few hours.

![2019-05-10_17-49-04.gif](https://user-images.githubusercontent.com/34610081/57558525-02037300-734c-11e9-9986-be5f11dfd169.gif)

Anyway, I'm going to clean up a bit and make a PR.

**Comment by mdtauk** [comment]
Throwing my 2 pence in, the cursor should not blink, but remain visible when a key is being held down and text is being entered into the console.  It would prevent a user typing in whilst the timer controlling the visibility is currently set to hidden.

**Comment by mKay00** [comment]
This is how it works now. When you type, the timer gets reset and the cursor is visible.

**Comment by raghavmallampalli** [comment]
I'm on Windows 10.19041, Terminal Preview 1.4.2652.0. I have a weird issue where the cursor blinks in PowerShell and cmd but not in WSL (Ubuntu 18.04 WSL2). Since there is a possibility that this might be a config issue I did not want to open a new issue, has anyone else experienced this and/or managed to fix it? It appears in zsh, sh and bash; with and without tmux attached.

**Comment by mnpenner** [comment]
I don't know what neovim is, but I'm experiencing this now with `zsh` and Ubuntu 20.04. PowerShell still blinks.

**Comment by logus2k** [comment]
> I don't know what neovim is, but I'm experiencing this now with `zsh` and Ubuntu 20.04. PowerShell still blinks.

Exactly the same here. Is there any update or new info to this? Tks

**Comment by Anutrix** [comment]
Same issue here making Windows Terminal impossible to use. Won't know if terminal has hanged if I don't see the cursor blinking.

**Comment by zadjii-msft** [comment]
@Anutrix in all likelyhood, you're seeing #11411, which should be fixed in 1.13. This original issue is _years_ old, so if you're seeing something like it, it's definitely not due to the same root cause as this thread 😉

**Comment by aradalvand** [comment]
Any updates on this? The cursor still doesn't blink in WSL/Bash.

**Comment by Anutrix** [comment]
As advised by @zadjii-msft I created a new ticket here https://github.com/microsoft/terminal/issues/13381.
