### ISSUE TITLE
Fix "blurry" new tab icon on 100% DPI

### ISSUE THREAD

**Issue by moxwel** [microsoft/terminal#7111]
# Description of the new feature/enhancement

This is a little graphic detail that I noticed long ago. The "new tab" icon in Windows Terminal (1.1.2021.0) **with 100% DPI scaling level** is somewhat _"blurry"_ or _"thick"_, in comparison of other "new tab" icons like Microsoft Edge.

![issue1](https://user-images.githubusercontent.com/49621788/88761685-99b1d480-d13d-11ea-976c-478121b280bd.png)

> This graphic detail **does not occur when the DPI scaling is at 125%**.
> ![issue2](https://user-images.githubusercontent.com/49621788/88761704-a5050000-d13d-11ea-9814-8d50870b1774.png)

# Proposed technical implementation details (optional)

Update the "new tab" icon to a more _"cleaner"_ version when DPI scaling is at 100%. An example:

![issue3](https://user-images.githubusercontent.com/49621788/88762129-9408be80-d13e-11ea-9748-52fcac304746.png)

**Comment by zadjii-msft** [comment]
Thanks for finding this! I'm gonna move this over to the [WinUI repo](https://github.com/microsoft/microsoft-ui-xaml), since I think they'll be better prepared to take care of this issue (and we can just ingest an updated version from them).

**Comment by DHowett** [comment]
This one is actually us; we have our own new tab button (made up of a split button with the plus glyph in it.)

**Comment by DHowett** [comment]
So, this needs @cinnamon-msft to weigh in. We actually had a PR that _fixed this completely_, just before 1.0, that we rejected on the grounds of "i don't like it". #5681.

**Comment by DHowett** [comment]
Assigning @cinnamon-msft by way of passing the baton. She's next up :smile:

**Comment by zadjii-msft** [comment]
I've had this tab open for months and _months_, and I think it's related to this issue?

https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.uselayoutrounding?view=winrt-19041

It's been so long that I honestly don't remember any more.

**Comment by moxwel** [comment]
What happens if `UseLayoutRounding` is set to `false` in [src/cascadia/TerminalApp/TabRowControl.xaml](https://github.com/microsoft/terminal/blob/main/src/cascadia/TerminalApp/TabRowControl.xaml#L30) ?

Just to know, I really don't know anything about that 😅

**Comment by zadjii-msft** [comment]
Hmm, seems like this was fixed sometime recently. 

![image](https://user-images.githubusercontent.com/18356694/179297002-fd49cafb-a429-4974-8081-af6ee304b55e.png)

Probably when we updated to Controlsv2. @moxwel do you see this on 1.14 (stable) or 1.15 (preview) anymore/?

**Comment by moxwel** [comment]
I still have not recieved 1.14 stable from Microsoft Store.
 
Just installed 1.15 preview from Store. The '+' symbol is still the same with 100% DPI.

![2](https://user-images.githubusercontent.com/49621788/179317680-9e8b271c-024b-4011-8c43-29eb2154564c.png)

On another PC with 125% DPI is normal.

![image](https://user-images.githubusercontent.com/49621788/179317802-b08c3ce1-7a5a-40bf-a8e2-c28140abe0f3.png)

I'm still using Windows 10. I've not tested it on Windows 11.

**Comment by zadjii-msft** [comment]
> I'm still using Windows 10. I've not tested it on Windows 11

Hmm. I wonder if that's actually why I'm seeing a difference. Perhaps the glyph is just hinted better in Segoe UI Fluent vs MDL2. I'll need to pull out an old Win10 laptop to confirm my suspicions. If that's the case, then we might be out of luck here on Win10 😕
