### ISSUE TITLE
Output should not keep scrolling down when manually scrolled up

### ISSUE THREAD

**Issue by sozercan** [microsoft/terminal#7222]
# Description of the new feature/enhancement
For example, when tailing/following a log, and cursor is at the bottom. I expect the output to be scrolled down automatically.

However, if I manually scroll up to certain spot (e.g., looking at a test failure), I don't want my current view keep getting scrolled down. It should lock in place when user manually scrolls up. When user scrolls all the way to the bottom, then it should resume tailing.

**Comment by 50Wliu** [comment]
It sounds like this was fixed in 1.2 Preview? https://github.com/microsoft/terminal/pull/6062#issuecomment-662550994

**Comment by sozercan** [comment]
This is still happening for me in 1.2.2022.0. Even when text is selected (didn't realize that was a requirement).

**Comment by zadjii-msft** [comment]
Is the entire buffer history full already? It seems like we don't stick the viewport to the right place when text is output and the buffer is already full, causing text circling.
