### ISSUE TITLE
Allow terminal color setting

### ISSUE THREAD

**Issue by bitcrazed** [microsoft/terminal#81]
_From @bbulkow on October 7, 2017 19:13_

Windows version: Microsoft Windows [Version 10.0.15063]

Please just add the ability to change colors. Or change the "dark blue on black" to just about anything else, like light blue on black, or dark blue on grey.

If I SSH into another host, the color for directory is dark blue on black. Whoever chose this is a masochist. The default should be something more sensible than dark blue on black - ANYTHING - and the ability to change the color is necessary.

Steps to reproduce: ssh pi@[any host]
$ ls /

You will see that the directory names are unreadable - dark blue on black.

People are asking for mouse and network and all kinds of things. Nonsense. Just allow me to ssh into another host and do an LS and read the output. SSH is the one feature I use most. And please don't tell me to use a windows ssh client like putty. The point of WSL is to give me the workflow I'm used to - and I just ssh around to hosts.

To ask me to change the colors on every host I log into is non-sense.

_Copied from original issue: Microsoft/WSL#2550_

**Comment by bitcrazed** [comment]
_From @Line117 on October 7, 2017 22:35_

https://www.youtube.com/watch?v=K7Vafhl7P0M

UPD: or https://conemu.github.io/

**Comment by bitcrazed** [comment]
_From @zadjii-msft on October 9, 2017 17:40_

So, there are actually a lot of options available for changing your colors:

1. You can change your default colors to something more pleasing. You can use [colortool](https://blogs.msdn.microsoft.com/commandline/2017/08/11/introducing-the-windows-console-colortool/) to change your defaults, and that should apply to your bash.exe/wsl.exe/ubuntu/suse/etc windows, assuming you haven't otherwise set any properties for them. This is the preferred method, because it's a lot easier to load entire color schemes with colortool than doing it manually.

For ex, `colortool -d solarized_dark` will give future console launches the "Solarized" color scheme.
![image](https://user-images.githubusercontent.com/18356694/31350934-eb3ff656-acdd-11e7-89e9-a2de39dd4e6b.png)

2. You can change the properties of your bash.exe window manually. 
 * right click ion the title bar of your console window, and click on properties:
![image](https://user-images.githubusercontent.com/18356694/31350492-4201da2e-acdc-11e7-8ab3-1539a4d3d824.png)
 * Use the "Colors" tab to change the values of the color table to something more pleasing.
![image](https://user-images.githubusercontent.com/18356694/31350510-52a9c062-acdc-11e7-849a-880cbef1d07a.png)
 * Hit okay to save and apply the changes.
Note that the Colors dialog is pretty much garbage and is really hard to use, hence colortool. 

Also note that unfortunately, colortool doesn't work with WSL and interop. It's a limitation of interop at the moment, but if anyone can find a way around that, [PR's are welcome :) ](https://github.com/Microsoft/console/tree/master/tools/ColorTool)

We've also [updated the default color scheme](https://blogs.msdn.microsoft.com/commandline/2017/08/02/updating-the-windows-console-colors/) as of the Fall Creator's Update, so if you choose to not change any properties at all right now, then when you get updated to FCU you'll get the new colors automatically.

**Comment by bitcrazed** [comment]
_From @bbulkow on October 9, 2017 17:50_

Thanks for the quick response.

Can you answer the simple question of whether colortool and similar will apply to ssh sessions?

Lots of previous ideas ( like changing LS_COLORS ) doesn't work when you SSH to another machine.

**Comment by bitcrazed** [comment]
_From @zadjii-msft on October 9, 2017 17:55_

Yes, it should. The actual colors that are displayed are controlled by the client terminal (in this case, conhost.exe), not the server (whatever's on the other end of ssh). So whenever an application on the server side writes text in "blue", it's up to the client to decide with which actual color "blue" is rendered in.

**Comment by bitcrazed** [comment]
_From @PhMajerus on October 24, 2017 2:15_

Just in case you're feeling adventurous...
I think you could have the colors set on the server if you wanted to.
What you need is an utility between your SSH server and the shell and apps that parses the VT sequences and convert all palette-specific sequences (colors, bright, ...) to RGB (in \e[38;5;r;g;bm style) according to a locally set palette.
This would increase the network traffic a bit, but would enable you to set your colors on the server side, regardless of client.

You can test this out by running the following:
bash 1> >(lolcat)
Colors should be set randomly by lolcat. Server-side palette utility would work in a similar fashion but swapping colors sequences on the fly.

**Comment by andybak** [comment]
Defaults matter and the defaults are terrible. The "dark blue on black" is unreadable for me.

**Comment by bitcrazed** [comment]
We agree, which is why we worked with our accessibility team during Creators Update to [update the default Console color palette](https://blogs.msdn.microsoft.com/commandline/2017/08/02/updating-the-windows-console-colors/) for the first time ever.

If you clean-install Windows 10 Creators Update or later, you'll get [the new default color palette](https://blogs.msdn.microsoft.com/commandline/2017/08/02/updating-the-windows-console-colors/).

If you upgrade from a previos Windows version, you'll keep your original defaults including the 0x0000ff deep navy blue on black - there was no way for us to upgrade existing installs to the new palette without potentially borking someone's carefully chosen color settings.

If you did upgrade and want the new color palette, you can do so by opening your Cmd instances (wherever they're pinned, and use [the Console ColorTool](https://blogs.msdn.microsoft.com/commandline/2017/08/11/introducing-the-windows-console-colortool/) to change your Consoles' palette to the new default, or any other you choose.

**Comment by pckilgore** [comment]
Not sure why this was moved from WSL, or why it was closed, because colortool does nothing to change the color scheme of my WSL console (on 17692).  Colortool works as expected with cmd consoles.

There is a workaround:  Open a cmd terminal then launch wsl from that terminal.

**Comment by bitcrazed** [comment]
This issue was moved to Console because color text rendering is primarily a Console issue, not WSL.

If a Linux application emits VT instructions that say "draw this text in Console's color palette index 1", the terminal draws the text in whatever it has configured in its current color palette.

If your Console's palette says the color at index 1 is  `0x0000ff`, then it'll be displayed in (the original) deep navy blue ... on black which is **horrible** on LCD screens ... which is why [we updated the default palette](https://blogs.msdn.microsoft.com/commandline/2017/08/02/updating-the-windows-console-colors/) for new Win10 installs).

If, on the other hand, your Console's color palette says the color at index 1 is `0x0037DA`, then you'll see our new, updated blue ...
![image](https://user-images.githubusercontent.com/961950/43096836-201daba2-8e6f-11e8-80d8-39b219248be8.png)

...which is MUCH more readable on LCD screens:
![image](https://user-images.githubusercontent.com/961950/43096882-4517499a-8e6f-11e8-9da2-355c9330eb37.png)

If you choose to set a different color at index 1, then you'll see whatever color you specify.

HOWEVER, if you use Linux tools that emit VT that says "display this text in `0x445566`", then Console renders the text using the requested color - the Console's color palette is ignored if specific RGB colors are specified by the generating app ... which is what you see when you pipe text through [lolcat](https://github.com/busyloop/lolcat):
![image](https://user-images.githubusercontent.com/961950/43097086-d9db8b40-8e6f-11e8-9268-cb8fffce9704.png)

**Comment by DhruvM7** [comment]
It works as expected in Command Prompt, but using this in PowerShell turns the background pink, so I'm afraid to use it. Will it affect only cmd and wsl, or powershell also? 

![tempsnip](https://user-images.githubusercontent.com/12984937/44271919-06857a00-a259-11e8-9d6f-1da09c2eb7a9.png)

**Comment by bitcrazed** [comment]
No. This is due to a quirk in the way Windows PowerShell changes PowerShell's default background color index (5) and the color itself (0x012456).

I'm working on some additional themes that will give you sane options for Windows PowerShell. Stay tuned!

**Comment by soerendip** [comment]
Why don't add these colors in the Properties window? I don't find an option to change specifically the dark blue to something else. Where can I change the color values in the palette?

**Comment by cpadilla** [comment]
I'd also like to comment on this issue as it seems like it's the closest solution to my use case.

I'm using WSL and I've painstakingly set my colors via the command prompt properties dialog.
![image](https://user-images.githubusercontent.com/1704172/48983265-9a69ac00-f0ba-11e8-87ad-e1a4c4fe7099.png)
![image](https://user-images.githubusercontent.com/1704172/48983272-a35a7d80-f0ba-11e8-9fe7-f1fd45340606.png)

In my linux configurations, I additionally set "color130", which seems to be used by vim for some reason. Unfortunately it looks like the command prompt only supports color0 - color15, so I end up with this ugly brown color for color130.
![image](https://user-images.githubusercontent.com/1704172/48983309-2b408780-f0bb-11e8-8b04-d042969584e5.png)

Is there any way to set a color above 15? Possibly through the registry?

You can use this command (in bash) to test the colors in the console:
```bash
tput setaf 130 && echo XXX
```

**Comment by DHowett** [comment]
@cpadilla I think 130 is one of the standard `xterm-256color` colors:

![image](https://user-images.githubusercontent.com/189190/48983420-6fc02900-f0a3-11e8-92ec-aa2b96458493.png)

Since they're from a fixed and quasi-standardized palette, I don't believe that any terminal emulator allows you to change them.

**Comment by zadjii-msft** [comment]
@cpadilla First off, your color scheme looks awesome, I'm definitely gonna copy that.

I think you're correct that we don't support setting above index 15 at the moment, but I don't believe there's any reason we couldn't. 

I've opened #313 to track that issue.

**Comment by cellcoresystems** [comment]
There is apossibility to change the default colors of the console.
Just go here eval **HKEY_CURRENT_USER/Console** with regedit 
and there you find **ColorTable00-15** tweak it to your needs ;)

**Comment by cellcoresystems** [comment]
> There is apossibility to change the default colors of the console.
> Just go to **HKEY_CURRENT_USER/Console** with regedit
> and there you find **ColorTable00-15** tweak it to your needs ;)

sorry its not working, it shows but does not affect the bash terminal

**Comment by NorbertWasilewski** [comment]
> > There is apossibility to change the default colors of the console.
> > Just go to **HKEY_CURRENT_USER/Console** with regedit
> > and there you find **ColorTable00-15** tweak it to your needs ;)
> 
> sorry its not working, it shows but does not affect the bash terminal

It does work. There is a 16 ColorTable* values, each mapped to console color. Comments color is stored in a second value (as you can see in Console Properties, it's a second colorbox). So you just need to replace `ColorTable01` with a color value you need.

**Comment by miniksa** [comment]
This has now turned into something like 5 different complaints, many of which are already solved.

We have color tool, we have registry settings, we added another property sheet to the console so you can adjust the terminal properties, we extended the VT sequences processed to set the color options...

All of these, I think, substantially improve this experience.

If there are further individual issues here, let's open new issues for each individual problem instead of continuing to pile on here.

Thanks.

**Comment by JoshDesmond** [comment]
I am still experiencing the single original issue with colors on PowerShell version.

The accepted solution for this issue on this [superuser thread](https://superuser.com/questions/1333946/openssh-via-powershell-vi-turns-prompt-blue) is to consider using a terminal emulator like putty. This issue should be re-opened.

**Comment by blixten85** [comment]
Why is there no pre-set themes for cmd.exe?
It's like recreating the wheel all over, per person.

**Comment by zadjii-msft** [comment]
@blixten85 Because `conhost.exe` (the application responsible for the `cmd.exe` window) is now officially in maintenance mode, and most new UI feature requests are being directed towards the Windows Terminal.

If you'd prefer stay on the vintage console, I'd recommend [ColorTool](https://github.com/Microsoft/Terminal/tree/master/src/tools/ColorTool).

**Comment by coleman-rik** [comment]
Silly thought, why can't WSL/WSL2 use a **Linux** console?  There are quite a number of consoles in various Linux distributions and every one without fail is superior to cmd.exe, conhost.exe, or whatever else Microsoft throws over the fence for Windows users to use.

It's just seems counter productive to install an entire Linux distribution on Windows and then be forced to use whatever console application Windows users are forced to use.  All of this *cross*talk; 
 -  WSL's console has horrible colors
 -  > We've updated the colors in this *windows* console application
-  WSL's console colors are **still** terrible
-  > Oh, the updated *windows* console isn't usable by WSL, try this **clunky** workaround 
-  WSL's console colors are **still** terrible
etc. etc. etc.

If Microsoft would just let users of WSL and WSL2 use *native* Linux terminals; Gnome Terminal, Konsole, Xfce Terminal, etc. then all of these issues would take care of themselves.  The other alternative would be to just wipe the Windows install (assuming you have that option) run an *actual* Linux distro and keep a VM with a Windows guest around for those pesky little Windows chores.

Of course that wouldn't help non WSL / WSL2 users.  I hear that, at least for **new** apps like the new Windows Terminal, Microsoft **is** working on updating the color pallets from the Win95 CRT display days.  So there's that.

**Comment by zadjii-msft** [comment]
@coleman-rik This thread's like, 5 years old. The Windows Console (conhost.exe) did not have a super intuitive way of changing the colors, sure. The Windows Terminal fares a lot better in that regard. If you've still got issues with the color schemes in the Terminal, well, you've come to the eight repo.

Plus, you've been able to run GUI applications in WSL for some time now. Feel free to go install `gnome-terminal` or whatever your preferred terminal application is from your package manager. 

So there's that.
