### ISSUE TITLE
strange bar appear while maximized

### ISSUE THREAD

**Issue by epiciskandar** [microsoft/terminal#8384]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.630] 
Windows Terminal version (if applicable): 1.4.3243.0

Any other software?
```

# Steps to reproduce

_initially, the Windows Taskbar is normally at the top, and always showing_
1. open Windows Terminal
2. maximized window
3. trigger fullscreen mode with F11
4. go to Windows `Taskbar Settings` and trigger on `Automatically hide the taskbar in desktop mode`
5. go back to Terminal and press F11 to exit fullscreen mode
6. a strange bar appears up to the title area, see this image:
**zoom in and look at the area above Terminal and close button**
![image](https://user-images.githubusercontent.com/1884240/100067232-f796c480-2e70-11eb-8b88-f7302ad70300.png)
(note that Windows Taskbar above already hided)
the bar has three tiny buttons: minimize, maximize and close, all are works.

sometimes after moving Terminal window or exit maximized status, that bar will disappear, but sometimes not.
if that bar does not disappear, Terminal cannot maximized to all area while the Windows Taskbar in `auto hide mode`

# Expected behavior

no strange bar appear, and maximize the window properly

# Actual behavior

sometimes cannot maximized Terminal with Taskbar autohided

**Comment by Don-Vito** [comment]
Wow.. that is a weird one 😄 . Does not reproduce for me: instead I simply have an used area in under the window - where the taskbar used to reside. Few questions:
1. Is it 100% reproducible for you or happens occasionally?
2. To reproduce the issue do you wait for taskbar to disappear before exiting the fullscreen? Trying understand if there is a timing issue.
3. Any details about your setup: how many monitors, with what scaling? Trying to understand if there is a scaling issue.

**Comment by epiciskandar** [comment]
> Is it 100% reproducible for you or happens occasionally?
yes, it is 100% reproduce.
> do you wait for taskbar to disappear before exiting the fullscreen?
yes, not time racing.everything happens flex
> how many monitors, with what scaling?
two monitor, with same 100% scaling, resolution 1920*1080.
this happens on both monitor, but firstly I found it on the secondary one, then reproduce this on primary one too.
I have another PC, with same Windows version, but the Terminal is preview ver(1.5.3242.0). and same thing can be reproduced.

**Comment by epiciskandar** [comment]
I remembered one step not listed, between step 2 and step 3, or say, before fullscreening Terminal, you need to open "Taskbar Settings" first.
after Terminal go to fullscreen, switch to that setting window by clicking `Alt + Tab`

**Comment by epiciskandar** [comment]
> Does not reproduce for me: instead I simply have an used area **under** the terminal window

for me, the taskbar is on the top of desktop

**Comment by Don-Vito** [comment]
> 
> 
> > Does not reproduce for me: instead I simply have an used area **under** the terminal window
> 
> for me, the taskbar is on the top of desktop

I missed that "tiny" part. Was able to reproduce it with debugger attached. 
Will try to take a look, unless the team has a direction.

IIRC there is some underlying window that is used for dragging - so my guess it is somehow not aligned with the island anymore.

**Comment by Don-Vito** [comment]
@zadjii-msft - I see it is not the first issue with full screen and auto-hide taskbar that caused the windows to be not aligned:

```
void NonClientIslandWindow::_SetIsFullscreen(const bool fullscreenEnabled)
{
    IslandWindow::_SetIsFullscreen(fullscreenEnabled);
    if (_titlebar)
    {
        _titlebar.Visibility(_IsTitlebarVisible() ? Visibility::Visible : Visibility::Collapsed);
    }
    // GH#4224 - When the auto-hide taskbar setting is enabled, then we don't
    // always get another window message to trigger us to remove the drag bar.
    // So, make sure to update the size of the drag region here, so that it
    // _definitely_ goes away.
    _ResizeDragBarWindow();
}
```

**Comment by DHowett** [comment]
@Don-Vito probably won’t be our last, either :smile: something about DwmExtendFrameIntoClientArea and WM_NCCALCSIZE occasionally make weird things like this happen :| and we haven’t quite nailed down all of them it seems!

**Comment by zadjii-msft** [comment]
What the dickens, that definitely repros for me. I have no idea why, but it's a real bug. 

I'll throw it in with the rest of the window shenanigans tracked in #1625. Thanks!

**Comment by Don-Vito** [comment]
@zadjii-msft - This definitely repros.. I tried to look at it and got a headache.. :smile: I will probably try to look at it again later on...

**Comment by zadjii-msft** [comment]
Good news everyone! Looks like this is resolved in recent Terminal builds. Not sure which exactly, but likely one of #11653 or #9737 fixed it. Thanks all!

**Comment by MarcoBuess** [comment]
@zadjii-msft its still happening for me on `1.20.11381.0`. On fullscreen the bar gets smaller but is still there. It will only disappear when windowed. Padding is set to `0` in my `settings.json`.

**Comment by zadjii-msft** [comment]
@MarcoBuess And to confirm, you're using an auto-hiding, top taskbar as well? Windows version 19045? 

This was closed out some 3 years ago now, it might be a recent regression, but I doubt that. We haven't done too much to mess with the windowing code over the last few releases. I also don't have a non-VM win10 machine handy with which to test easily 😕

**Comment by MarcoBuess** [comment]
@zadjii-msft Actually I did recently before upgrading to Windows 11, where I have the issue even without the hiding taskbar situation.
